// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product_service.proto

package io.bokun.inventory.service.product.grpc;

/**
 * Protobuf type {@code io.bokun.inventory.service.product.grpc.GetProductMappingsRequest}
 */
public  final class GetProductMappingsRequest extends
    com.google.protobuf.GeneratedMessageLite<
        GetProductMappingsRequest, GetProductMappingsRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.service.product.grpc.GetProductMappingsRequest)
    GetProductMappingsRequestOrBuilder {
  private GetProductMappingsRequest() {
    pluginId_ = "";
    bokunProducts_ = emptyProtobufList();
  }
  public static final int PLUGINID_FIELD_NUMBER = 1;
  private java.lang.String pluginId_;
  /**
   * <pre>
   * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
   * </pre>
   *
   * <code>string pluginId = 1;</code>
   * @return The pluginId.
   */
  @java.lang.Override
  public java.lang.String getPluginId() {
    return pluginId_;
  }
  /**
   * <pre>
   * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
   * </pre>
   *
   * <code>string pluginId = 1;</code>
   * @return The bytes for pluginId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPluginIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(pluginId_);
  }
  /**
   * <pre>
   * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
   * </pre>
   *
   * <code>string pluginId = 1;</code>
   * @param value The pluginId to set.
   */
  private void setPluginId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    pluginId_ = value;
  }
  /**
   * <pre>
   * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
   * </pre>
   *
   * <code>string pluginId = 1;</code>
   */
  private void clearPluginId() {
    
    pluginId_ = getDefaultInstance().getPluginId();
  }
  /**
   * <pre>
   * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
   * </pre>
   *
   * <code>string pluginId = 1;</code>
   * @param value The bytes for pluginId to set.
   */
  private void setPluginIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    pluginId_ = value.toStringUtf8();
    
  }

  public static final int VENDORID_FIELD_NUMBER = 2;
  private long vendorId_;
  /**
   * <pre>
   * vendor to get mapped products for. Mandatory.
   * </pre>
   *
   * <code>int64 vendorId = 2;</code>
   * @return The vendorId.
   */
  @java.lang.Override
  public long getVendorId() {
    return vendorId_;
  }
  /**
   * <pre>
   * vendor to get mapped products for. Mandatory.
   * </pre>
   *
   * <code>int64 vendorId = 2;</code>
   * @param value The vendorId to set.
   */
  private void setVendorId(long value) {
    
    vendorId_ = value;
  }
  /**
   * <pre>
   * vendor to get mapped products for. Mandatory.
   * </pre>
   *
   * <code>int64 vendorId = 2;</code>
   */
  private void clearVendorId() {
    
    vendorId_ = 0L;
  }

  public static final int BOKUNPRODUCTS_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<io.bokun.inventory.service.common.grpc.BokunProduct> bokunProducts_;
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  @java.lang.Override
  public java.util.List<io.bokun.inventory.service.common.grpc.BokunProduct> getBokunProductsList() {
    return bokunProducts_;
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  public java.util.List<? extends io.bokun.inventory.service.common.grpc.BokunProductOrBuilder> 
      getBokunProductsOrBuilderList() {
    return bokunProducts_;
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  @java.lang.Override
  public int getBokunProductsCount() {
    return bokunProducts_.size();
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.service.common.grpc.BokunProduct getBokunProducts(int index) {
    return bokunProducts_.get(index);
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  public io.bokun.inventory.service.common.grpc.BokunProductOrBuilder getBokunProductsOrBuilder(
      int index) {
    return bokunProducts_.get(index);
  }
  private void ensureBokunProductsIsMutable() {
    com.google.protobuf.Internal.ProtobufList<io.bokun.inventory.service.common.grpc.BokunProduct> tmp = bokunProducts_;
    if (!tmp.isModifiable()) {
      bokunProducts_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  private void setBokunProducts(
      int index, io.bokun.inventory.service.common.grpc.BokunProduct value) {
    value.getClass();
  ensureBokunProductsIsMutable();
    bokunProducts_.set(index, value);
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  private void addBokunProducts(io.bokun.inventory.service.common.grpc.BokunProduct value) {
    value.getClass();
  ensureBokunProductsIsMutable();
    bokunProducts_.add(value);
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  private void addBokunProducts(
      int index, io.bokun.inventory.service.common.grpc.BokunProduct value) {
    value.getClass();
  ensureBokunProductsIsMutable();
    bokunProducts_.add(index, value);
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  private void addAllBokunProducts(
      java.lang.Iterable<? extends io.bokun.inventory.service.common.grpc.BokunProduct> values) {
    ensureBokunProductsIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, bokunProducts_);
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  private void clearBokunProducts() {
    bokunProducts_ = emptyProtobufList();
  }
  /**
   * <pre>
   * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
   * If the list has at least one element, it will try to find mappings for specified product(s) only.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
   */
  private void removeBokunProducts(int index) {
    ensureBokunProductsIsMutable();
    bokunProducts_.remove(index);
  }

  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.service.product.grpc.GetProductMappingsRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code io.bokun.inventory.service.product.grpc.GetProductMappingsRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.service.product.grpc.GetProductMappingsRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.service.product.grpc.GetProductMappingsRequest)
      io.bokun.inventory.service.product.grpc.GetProductMappingsRequestOrBuilder {
    // Construct using io.bokun.inventory.service.product.grpc.GetProductMappingsRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
     * </pre>
     *
     * <code>string pluginId = 1;</code>
     * @return The pluginId.
     */
    @java.lang.Override
    public java.lang.String getPluginId() {
      return instance.getPluginId();
    }
    /**
     * <pre>
     * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
     * </pre>
     *
     * <code>string pluginId = 1;</code>
     * @return The bytes for pluginId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPluginIdBytes() {
      return instance.getPluginIdBytes();
    }
    /**
     * <pre>
     * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
     * </pre>
     *
     * <code>string pluginId = 1;</code>
     * @param value The pluginId to set.
     * @return This builder for chaining.
     */
    public Builder setPluginId(
        java.lang.String value) {
      copyOnWrite();
      instance.setPluginId(value);
      return this;
    }
    /**
     * <pre>
     * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
     * </pre>
     *
     * <code>string pluginId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPluginId() {
      copyOnWrite();
      instance.clearPluginId();
      return this;
    }
    /**
     * <pre>
     * plugin id to get mapped products for. Optional: if passed, it will filter by given plugin definition id, otherwise all definitions will match.
     * </pre>
     *
     * <code>string pluginId = 1;</code>
     * @param value The bytes for pluginId to set.
     * @return This builder for chaining.
     */
    public Builder setPluginIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPluginIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * vendor to get mapped products for. Mandatory.
     * </pre>
     *
     * <code>int64 vendorId = 2;</code>
     * @return The vendorId.
     */
    @java.lang.Override
    public long getVendorId() {
      return instance.getVendorId();
    }
    /**
     * <pre>
     * vendor to get mapped products for. Mandatory.
     * </pre>
     *
     * <code>int64 vendorId = 2;</code>
     * @param value The vendorId to set.
     * @return This builder for chaining.
     */
    public Builder setVendorId(long value) {
      copyOnWrite();
      instance.setVendorId(value);
      return this;
    }
    /**
     * <pre>
     * vendor to get mapped products for. Mandatory.
     * </pre>
     *
     * <code>int64 vendorId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearVendorId() {
      copyOnWrite();
      instance.clearVendorId();
      return this;
    }

    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    @java.lang.Override
    public java.util.List<io.bokun.inventory.service.common.grpc.BokunProduct> getBokunProductsList() {
      return java.util.Collections.unmodifiableList(
          instance.getBokunProductsList());
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    @java.lang.Override
    public int getBokunProductsCount() {
      return instance.getBokunProductsCount();
    }/**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.service.common.grpc.BokunProduct getBokunProducts(int index) {
      return instance.getBokunProducts(index);
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder setBokunProducts(
        int index, io.bokun.inventory.service.common.grpc.BokunProduct value) {
      copyOnWrite();
      instance.setBokunProducts(index, value);
      return this;
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder setBokunProducts(
        int index, io.bokun.inventory.service.common.grpc.BokunProduct.Builder builderForValue) {
      copyOnWrite();
      instance.setBokunProducts(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder addBokunProducts(io.bokun.inventory.service.common.grpc.BokunProduct value) {
      copyOnWrite();
      instance.addBokunProducts(value);
      return this;
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder addBokunProducts(
        int index, io.bokun.inventory.service.common.grpc.BokunProduct value) {
      copyOnWrite();
      instance.addBokunProducts(index, value);
      return this;
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder addBokunProducts(
        io.bokun.inventory.service.common.grpc.BokunProduct.Builder builderForValue) {
      copyOnWrite();
      instance.addBokunProducts(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder addBokunProducts(
        int index, io.bokun.inventory.service.common.grpc.BokunProduct.Builder builderForValue) {
      copyOnWrite();
      instance.addBokunProducts(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder addAllBokunProducts(
        java.lang.Iterable<? extends io.bokun.inventory.service.common.grpc.BokunProduct> values) {
      copyOnWrite();
      instance.addAllBokunProducts(values);
      return this;
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder clearBokunProducts() {
      copyOnWrite();
      instance.clearBokunProducts();
      return this;
    }
    /**
     * <pre>
     * For which Bokun products to get mapping for? If the list is empty/null, it will return all mappings.
     * If the list has at least one element, it will try to find mappings for specified product(s) only.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct bokunProducts = 3;</code>
     */
    public Builder removeBokunProducts(int index) {
      copyOnWrite();
      instance.removeBokunProducts(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.service.product.grpc.GetProductMappingsRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.service.product.grpc.GetProductMappingsRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "pluginId_",
            "vendorId_",
            "bokunProducts_",
            io.bokun.inventory.service.common.grpc.BokunProduct.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0001\u0000\u0001\u0208\u0002\u0002" +
              "\u0003\u001b";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.service.product.grpc.GetProductMappingsRequest> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.service.product.grpc.GetProductMappingsRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.service.product.grpc.GetProductMappingsRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.service.product.grpc.GetProductMappingsRequest)
  private static final io.bokun.inventory.service.product.grpc.GetProductMappingsRequest DEFAULT_INSTANCE;
  static {
    GetProductMappingsRequest defaultInstance = new GetProductMappingsRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetProductMappingsRequest.class, defaultInstance);
  }

  public static io.bokun.inventory.service.product.grpc.GetProductMappingsRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetProductMappingsRequest> PARSER;

  public static com.google.protobuf.Parser<GetProductMappingsRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

