// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product_service.proto

package io.bokun.inventory.service.product.grpc;

public interface SearchProductsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.service.product.grpc.SearchProductsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Mandatory.
   * </pre>
   *
   * <code>string pluginId = 1;</code>
   * @return The pluginId.
   */
  java.lang.String getPluginId();
  /**
   * <pre>
   * Mandatory.
   * </pre>
   *
   * <code>string pluginId = 1;</code>
   * @return The bytes for pluginId.
   */
  com.google.protobuf.ByteString
      getPluginIdBytes();

  /**
   * <pre>
   * Mandatory
   * </pre>
   *
   * <code>int64 vendorId = 2;</code>
   * @return The vendorId.
   */
  long getVendorId();

  /**
   * <pre>
   * Name of product, optional.
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of product, optional.
   * </pre>
   *
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * ISO ALPHA-2 code, optional
   * </pre>
   *
   * <code>string country = 4;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <pre>
   * ISO ALPHA-2 code, optional
   * </pre>
   *
   * <code>string country = 4;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <pre>
   * City to get products for. Optional.
   * </pre>
   *
   * <code>string city = 5;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <pre>
   * City to get products for. Optional.
   * </pre>
   *
   * <code>string city = 5;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
