// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory_service_common.proto

package io.bokun.inventory.service.common.grpc;

public interface BokunToExternalMappingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.service.common.grpc.BokunToExternalMapping)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Might refer to any type within Bokun, the context will reflect circumstances (e.g. might mean pricing category id in Bokun). Mandatory.
   * </pre>
   *
   * <code>string bokunId = 1;</code>
   * @return The bokunId.
   */
  java.lang.String getBokunId();
  /**
   * <pre>
   * Might refer to any type within Bokun, the context will reflect circumstances (e.g. might mean pricing category id in Bokun). Mandatory.
   * </pre>
   *
   * <code>string bokunId = 1;</code>
   * @return The bytes for bokunId.
   */
  com.google.protobuf.ByteString
      getBokunIdBytes();

  /**
   * <pre>
   * Whatever counterpart there is on the external system. Mandatory.
   * </pre>
   *
   * <code>string externalId = 2;</code>
   * @return The externalId.
   */
  java.lang.String getExternalId();
  /**
   * <pre>
   * Whatever counterpart there is on the external system. Mandatory.
   * </pre>
   *
   * <code>string externalId = 2;</code>
   * @return The bytes for externalId.
   */
  com.google.protobuf.ByteString
      getExternalIdBytes();
}
