// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: inventory_service_common.proto

package io.bokun.inventory.service.common.grpc;

public final class InventoryServiceCommon {
  private InventoryServiceCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
