// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin_service.proto

package io.bokun.inventory.service.plugin.grpc;

public interface DeletePluginConfigurationRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.service.plugin.grpc.DeletePluginConfigurationRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int64 vendorId = 1;</code>
   * @return The vendorId.
   */
  long getVendorId();

  /**
   * <code>string pluginId = 2;</code>
   * @return The pluginId.
   */
  java.lang.String getPluginId();
  /**
   * <code>string pluginId = 2;</code>
   * @return The bytes for pluginId.
   */
  com.google.protobuf.ByteString
      getPluginIdBytes();
}
