// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin_service.proto

package io.bokun.inventory.service.plugin.grpc;

public interface GetPluginVendorsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.service.plugin.grpc.GetPluginVendorsResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated int64 vendorIds = 1;</code>
   * @return A list containing the vendorIds.
   */
  java.util.List<java.lang.Long> getVendorIdsList();
  /**
   * <code>repeated int64 vendorIds = 1;</code>
   * @return The count of vendorIds.
   */
  int getVendorIdsCount();
  /**
   * <code>repeated int64 vendorIds = 1;</code>
   * @param index The index of the element to return.
   * @return The vendorIds at the given index.
   */
  long getVendorIds(int index);
}
