// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface AddressOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.Address)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string addressLine1 = 1;</code>
   * @return The addressLine1.
   */
  java.lang.String getAddressLine1();
  /**
   * <code>string addressLine1 = 1;</code>
   * @return The bytes for addressLine1.
   */
  com.google.protobuf.ByteString
      getAddressLine1Bytes();

  /**
   * <code>string addressLine2 = 2;</code>
   * @return The addressLine2.
   */
  java.lang.String getAddressLine2();
  /**
   * <code>string addressLine2 = 2;</code>
   * @return The bytes for addressLine2.
   */
  com.google.protobuf.ByteString
      getAddressLine2Bytes();

  /**
   * <code>string addressLine3 = 3;</code>
   * @return The addressLine3.
   */
  java.lang.String getAddressLine3();
  /**
   * <code>string addressLine3 = 3;</code>
   * @return The bytes for addressLine3.
   */
  com.google.protobuf.ByteString
      getAddressLine3Bytes();

  /**
   * <code>string city = 4;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <code>string city = 4;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();

  /**
   * <code>string state = 5;</code>
   * @return The state.
   */
  java.lang.String getState();
  /**
   * <code>string state = 5;</code>
   * @return The bytes for state.
   */
  com.google.protobuf.ByteString
      getStateBytes();

  /**
   * <code>string postalCode = 6;</code>
   * @return The postalCode.
   */
  java.lang.String getPostalCode();
  /**
   * <code>string postalCode = 6;</code>
   * @return The bytes for postalCode.
   */
  com.google.protobuf.ByteString
      getPostalCodeBytes();

  /**
   * <code>string countryCode = 7;</code>
   * @return The countryCode.
   */
  java.lang.String getCountryCode();
  /**
   * <code>string countryCode = 7;</code>
   * @return The bytes for countryCode.
   */
  com.google.protobuf.ByteString
      getCountryCodeBytes();

  /**
   * <code>.io.bokun.inventory.common.api.grpc.GeoPoint geoPoint = 8;</code>
   * @return Whether the geoPoint field is set.
   */
  boolean hasGeoPoint();
  /**
   * <code>.io.bokun.inventory.common.api.grpc.GeoPoint geoPoint = 8;</code>
   * @return The geoPoint.
   */
  io.bokun.inventory.common.api.grpc.GeoPoint getGeoPoint();

  /**
   * <code>.io.bokun.inventory.common.api.grpc.UnLocode unLocode = 9;</code>
   * @return Whether the unLocode field is set.
   */
  boolean hasUnLocode();
  /**
   * <code>.io.bokun.inventory.common.api.grpc.UnLocode unLocode = 9;</code>
   * @return The unLocode.
   */
  io.bokun.inventory.common.api.grpc.UnLocode getUnLocode();
}
