// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * <pre>
 * A brief information about a product. It is a subset of ProductDescription properties
 * </pre>
 *
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.BasicProductInfo}
 */
public  final class BasicProductInfo extends
    com.google.protobuf.GeneratedMessageLite<
        BasicProductInfo, BasicProductInfo.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.BasicProductInfo)
    BasicProductInfoOrBuilder {
  private BasicProductInfo() {
    id_ = "";
    name_ = "";
    description_ = "";
    pricingCategories_ = emptyProtobufList();
    cities_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
    countries_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <pre>
   * Product id of remote system. Mandatory.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <pre>
   * Product id of remote system. Mandatory.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <pre>
   * Product id of remote system. Mandatory.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <pre>
   * Product id of remote system. Mandatory.
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <pre>
   * Product id of remote system. Mandatory.
   * </pre>
   *
   * <code>string id = 1;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private java.lang.String name_;
  /**
   * <pre>
   * Product name of remote system. Mandatory.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <pre>
   * Product name of remote system. Mandatory.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <pre>
   * Product name of remote system. Mandatory.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @param value The name to set.
   */
  private void setName(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    name_ = value;
  }
  /**
   * <pre>
   * Product name of remote system. Mandatory.
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <pre>
   * Product name of remote system. Mandatory.
   * </pre>
   *
   * <code>string name = 2;</code>
   * @param value The bytes for name to set.
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    name_ = value.toStringUtf8();
    
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private java.lang.String description_;
  /**
   * <pre>
   * Product description of remote system. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <pre>
   * Product description of remote system. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <pre>
   * Product description of remote system. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <pre>
   * Product description of remote system. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   */
  private void clearDescription() {
    
    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <pre>
   * Product description of remote system. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();
    
  }

  public static final int PRICINGCATEGORIES_FIELD_NUMBER = 4;
  private com.google.protobuf.Internal.ProtobufList<io.bokun.inventory.common.api.grpc.PricingCategory> pricingCategories_;
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  @java.lang.Override
  public java.util.List<io.bokun.inventory.common.api.grpc.PricingCategory> getPricingCategoriesList() {
    return pricingCategories_;
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  public java.util.List<? extends io.bokun.inventory.common.api.grpc.PricingCategoryOrBuilder> 
      getPricingCategoriesOrBuilderList() {
    return pricingCategories_;
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  @java.lang.Override
  public int getPricingCategoriesCount() {
    return pricingCategories_.size();
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.PricingCategory getPricingCategories(int index) {
    return pricingCategories_.get(index);
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  public io.bokun.inventory.common.api.grpc.PricingCategoryOrBuilder getPricingCategoriesOrBuilder(
      int index) {
    return pricingCategories_.get(index);
  }
  private void ensurePricingCategoriesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<io.bokun.inventory.common.api.grpc.PricingCategory> tmp = pricingCategories_;
    if (!tmp.isModifiable()) {
      pricingCategories_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }

  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  private void setPricingCategories(
      int index, io.bokun.inventory.common.api.grpc.PricingCategory value) {
    value.getClass();
  ensurePricingCategoriesIsMutable();
    pricingCategories_.set(index, value);
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  private void addPricingCategories(io.bokun.inventory.common.api.grpc.PricingCategory value) {
    value.getClass();
  ensurePricingCategoriesIsMutable();
    pricingCategories_.add(value);
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  private void addPricingCategories(
      int index, io.bokun.inventory.common.api.grpc.PricingCategory value) {
    value.getClass();
  ensurePricingCategoriesIsMutable();
    pricingCategories_.add(index, value);
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  private void addAllPricingCategories(
      java.lang.Iterable<? extends io.bokun.inventory.common.api.grpc.PricingCategory> values) {
    ensurePricingCategoriesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, pricingCategories_);
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  private void clearPricingCategories() {
    pricingCategories_ = emptyProtobufList();
  }
  /**
   * <pre>
   * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
   * This refers to pricing categories of the remote system.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
   */
  private void removePricingCategories(int index) {
    ensurePricingCategoriesIsMutable();
    pricingCategories_.remove(index);
  }

  public static final int CITIES_FIELD_NUMBER = 5;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> cities_;
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   * @return A list containing the cities.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getCitiesList() {
    return cities_;
  }
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   * @return The count of cities.
   */
  @java.lang.Override
  public int getCitiesCount() {
    return cities_.size();
  }
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   * @param index The index of the element to return.
   * @return The cities at the given index.
   */
  @java.lang.Override
  public java.lang.String getCities(int index) {
    return cities_.get(index);
  }
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the cities at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCitiesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        cities_.get(index));
  }
  private void ensureCitiesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        cities_;  if (!tmp.isModifiable()) {
      cities_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   * @param index The index to set the value at.
   * @param value The cities to set.
   */
  private void setCities(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureCitiesIsMutable();
    cities_.set(index, value);
  }
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   * @param value The cities to add.
   */
  private void addCities(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureCitiesIsMutable();
    cities_.add(value);
  }
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   * @param values The cities to add.
   */
  private void addAllCities(
      java.lang.Iterable<java.lang.String> values) {
    ensureCitiesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, cities_);
  }
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   */
  private void clearCities() {
    cities_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
   * Multiple items means this product is for multiple cities.
   * </pre>
   *
   * <code>repeated string cities = 5;</code>
   * @param value The bytes of the cities to add.
   */
  private void addCitiesBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureCitiesIsMutable();
    cities_.add(value.toStringUtf8());
  }

  public static final int COUNTRIES_FIELD_NUMBER = 6;
  private com.google.protobuf.Internal.ProtobufList<java.lang.String> countries_;
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   * @return A list containing the countries.
   */
  @java.lang.Override
  public java.util.List<java.lang.String> getCountriesList() {
    return countries_;
  }
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   * @return The count of countries.
   */
  @java.lang.Override
  public int getCountriesCount() {
    return countries_.size();
  }
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   * @param index The index of the element to return.
   * @return The countries at the given index.
   */
  @java.lang.Override
  public java.lang.String getCountries(int index) {
    return countries_.get(index);
  }
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   * @param index The index of the value to return.
   * @return The bytes of the countries at the given index.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCountriesBytes(int index) {
    return com.google.protobuf.ByteString.copyFromUtf8(
        countries_.get(index));
  }
  private void ensureCountriesIsMutable() {
    com.google.protobuf.Internal.ProtobufList<java.lang.String> tmp =
        countries_;  if (!tmp.isModifiable()) {
      countries_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
     }
  }
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   * @param index The index to set the value at.
   * @param value The countries to set.
   */
  private void setCountries(
      int index, java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureCountriesIsMutable();
    countries_.set(index, value);
  }
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   * @param value The countries to add.
   */
  private void addCountries(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  ensureCountriesIsMutable();
    countries_.add(value);
  }
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   * @param values The countries to add.
   */
  private void addAllCountries(
      java.lang.Iterable<java.lang.String> values) {
    ensureCountriesIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, countries_);
  }
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   */
  private void clearCountries() {
    countries_ = com.google.protobuf.GeneratedMessageLite.emptyProtobufList();
  }
  /**
   * <pre>
   * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
   * Multiple items means this product is for multiple countries.
   * </pre>
   *
   * <code>repeated string countries = 6;</code>
   * @param value The bytes of the countries to add.
   */
  private void addCountriesBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    ensureCountriesIsMutable();
    countries_.add(value.toStringUtf8());
  }

  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BasicProductInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.BasicProductInfo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * A brief information about a product. It is a subset of ProductDescription properties
   * </pre>
   *
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.BasicProductInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.BasicProductInfo, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.BasicProductInfo)
      io.bokun.inventory.common.api.grpc.BasicProductInfoOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.BasicProductInfo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Product id of remote system. Mandatory.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <pre>
     * Product id of remote system. Mandatory.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <pre>
     * Product id of remote system. Mandatory.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <pre>
     * Product id of remote system. Mandatory.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <pre>
     * Product id of remote system. Mandatory.
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Product name of remote system. Mandatory.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <pre>
     * Product name of remote system. Mandatory.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <pre>
     * Product name of remote system. Mandatory.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <pre>
     * Product name of remote system. Mandatory.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <pre>
     * Product name of remote system. Mandatory.
     * </pre>
     *
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <pre>
     * Product description of remote system. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <pre>
     * Product description of remote system. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <pre>
     * Product description of remote system. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <pre>
     * Product description of remote system. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <pre>
     * Product description of remote system. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    @java.lang.Override
    public java.util.List<io.bokun.inventory.common.api.grpc.PricingCategory> getPricingCategoriesList() {
      return java.util.Collections.unmodifiableList(
          instance.getPricingCategoriesList());
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    @java.lang.Override
    public int getPricingCategoriesCount() {
      return instance.getPricingCategoriesCount();
    }/**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.PricingCategory getPricingCategories(int index) {
      return instance.getPricingCategories(index);
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder setPricingCategories(
        int index, io.bokun.inventory.common.api.grpc.PricingCategory value) {
      copyOnWrite();
      instance.setPricingCategories(index, value);
      return this;
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder setPricingCategories(
        int index, io.bokun.inventory.common.api.grpc.PricingCategory.Builder builderForValue) {
      copyOnWrite();
      instance.setPricingCategories(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder addPricingCategories(io.bokun.inventory.common.api.grpc.PricingCategory value) {
      copyOnWrite();
      instance.addPricingCategories(value);
      return this;
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder addPricingCategories(
        int index, io.bokun.inventory.common.api.grpc.PricingCategory value) {
      copyOnWrite();
      instance.addPricingCategories(index, value);
      return this;
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder addPricingCategories(
        io.bokun.inventory.common.api.grpc.PricingCategory.Builder builderForValue) {
      copyOnWrite();
      instance.addPricingCategories(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder addPricingCategories(
        int index, io.bokun.inventory.common.api.grpc.PricingCategory.Builder builderForValue) {
      copyOnWrite();
      instance.addPricingCategories(index,
          builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder addAllPricingCategories(
        java.lang.Iterable<? extends io.bokun.inventory.common.api.grpc.PricingCategory> values) {
      copyOnWrite();
      instance.addAllPricingCategories(values);
      return this;
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder clearPricingCategories() {
      copyOnWrite();
      instance.clearPricingCategories();
      return this;
    }
    /**
     * <pre>
     * Product categories this product is sold at. Optional - they will be shown for information purposes if set.
     * This refers to pricing categories of the remote system.
     * </pre>
     *
     * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategory pricingCategories = 4;</code>
     */
    public Builder removePricingCategories(int index) {
      copyOnWrite();
      instance.removePricingCategories(index);
      return this;
    }

    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @return A list containing the cities.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getCitiesList() {
      return java.util.Collections.unmodifiableList(
          instance.getCitiesList());
    }
    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @return The count of cities.
     */
    @java.lang.Override
    public int getCitiesCount() {
      return instance.getCitiesCount();
    }
    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @param index The index of the element to return.
     * @return The cities at the given index.
     */
    @java.lang.Override
    public java.lang.String getCities(int index) {
      return instance.getCities(index);
    }
    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cities at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCitiesBytes(int index) {
      return instance.getCitiesBytes(index);
    }
    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @param index The index to set the value at.
     * @param value The cities to set.
     * @return This builder for chaining.
     */
    public Builder setCities(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setCities(index, value);
      return this;
    }
    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @param value The cities to add.
     * @return This builder for chaining.
     */
    public Builder addCities(
        java.lang.String value) {
      copyOnWrite();
      instance.addCities(value);
      return this;
    }
    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @param values The cities to add.
     * @return This builder for chaining.
     */
    public Builder addAllCities(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllCities(values);
      return this;
    }
    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCities() {
      copyOnWrite();
      instance.clearCities();
      return this;
    }
    /**
     * <pre>
     * City name where this product is served at. Optional (if product is not applicable to any city, e.g. Lava Tours).
     * Multiple items means this product is for multiple cities.
     * </pre>
     *
     * <code>repeated string cities = 5;</code>
     * @param value The bytes of the cities to add.
     * @return This builder for chaining.
     */
    public Builder addCitiesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addCitiesBytes(value);
      return this;
    }

    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @return A list containing the countries.
     */
    @java.lang.Override
    public java.util.List<java.lang.String>
        getCountriesList() {
      return java.util.Collections.unmodifiableList(
          instance.getCountriesList());
    }
    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @return The count of countries.
     */
    @java.lang.Override
    public int getCountriesCount() {
      return instance.getCountriesCount();
    }
    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @param index The index of the element to return.
     * @return The countries at the given index.
     */
    @java.lang.Override
    public java.lang.String getCountries(int index) {
      return instance.getCountries(index);
    }
    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the countries at the given index.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCountriesBytes(int index) {
      return instance.getCountriesBytes(index);
    }
    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @param index The index to set the value at.
     * @param value The countries to set.
     * @return This builder for chaining.
     */
    public Builder setCountries(
        int index, java.lang.String value) {
      copyOnWrite();
      instance.setCountries(index, value);
      return this;
    }
    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @param value The countries to add.
     * @return This builder for chaining.
     */
    public Builder addCountries(
        java.lang.String value) {
      copyOnWrite();
      instance.addCountries(value);
      return this;
    }
    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @param values The countries to add.
     * @return This builder for chaining.
     */
    public Builder addAllCountries(
        java.lang.Iterable<java.lang.String> values) {
      copyOnWrite();
      instance.addAllCountries(values);
      return this;
    }
    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearCountries() {
      copyOnWrite();
      instance.clearCountries();
      return this;
    }
    /**
     * <pre>
     * ISO ALPHA-2 codes. Optional (inventory service may not set any country if plugin returns invalid data).
     * Multiple items means this product is for multiple countries.
     * </pre>
     *
     * <code>repeated string countries = 6;</code>
     * @param value The bytes of the countries to add.
     * @return This builder for chaining.
     */
    public Builder addCountriesBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.addCountriesBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.BasicProductInfo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.BasicProductInfo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "name_",
            "description_",
            "pricingCategories_",
            io.bokun.inventory.common.api.grpc.PricingCategory.class,
            "cities_",
            "countries_",
          };
          java.lang.String info =
              "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0003\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u001b\u0005\u021a\u0006\u021a";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.BasicProductInfo> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.BasicProductInfo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.BasicProductInfo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.BasicProductInfo)
  private static final io.bokun.inventory.common.api.grpc.BasicProductInfo DEFAULT_INSTANCE;
  static {
    BasicProductInfo defaultInstance = new BasicProductInfo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BasicProductInfo.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.BasicProductInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BasicProductInfo> PARSER;

  public static com.google.protobuf.Parser<BasicProductInfo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

