// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * <pre>
 * Booking source used in booking
 * </pre>
 *
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.BookingSource}
 */
public  final class BookingSource extends
    com.google.protobuf.GeneratedMessageLite<
        BookingSource, BookingSource.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.BookingSource)
    BookingSourceOrBuilder {
  private BookingSource() {
  }
  public static final int SEGMENT_FIELD_NUMBER = 1;
  private int segment_;
  /**
   * <pre>
   * Booking sales segment. Mandatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
   * @return The enum numeric value on the wire for segment.
   */
  @java.lang.Override
  public int getSegmentValue() {
    return segment_;
  }
  /**
   * <pre>
   * Booking sales segment. Mandatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
   * @return The segment.
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.SalesSegment getSegment() {
    io.bokun.inventory.common.api.grpc.SalesSegment result = io.bokun.inventory.common.api.grpc.SalesSegment.forNumber(segment_);
    return result == null ? io.bokun.inventory.common.api.grpc.SalesSegment.UNRECOGNIZED : result;
  }
  /**
   * <pre>
   * Booking sales segment. Mandatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
   * @param value The enum numeric value on the wire for segment to set.
   */
  private void setSegmentValue(int value) {
      segment_ = value;
  }
  /**
   * <pre>
   * Booking sales segment. Mandatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
   * @param value The segment to set.
   */
  private void setSegment(io.bokun.inventory.common.api.grpc.SalesSegment value) {
    segment_ = value.getNumber();
    
  }
  /**
   * <pre>
   * Booking sales segment. Mandatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
   */
  private void clearSegment() {
    
    segment_ = 0;
  }

  public static final int BOOKINGCHANNEL_FIELD_NUMBER = 2;
  private io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel_;
  /**
   * <pre>
   * Booking channel. Obligatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
   */
  @java.lang.Override
  public boolean hasBookingChannel() {
    return bookingChannel_ != null;
  }
  /**
   * <pre>
   * Booking channel. Obligatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel getBookingChannel() {
    return bookingChannel_ == null ? io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel.getDefaultInstance() : bookingChannel_;
  }
  /**
   * <pre>
   * Booking channel. Obligatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
   */
  private void setBookingChannel(io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel value) {
    value.getClass();
  bookingChannel_ = value;
    
    }
  /**
   * <pre>
   * Booking channel. Obligatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeBookingChannel(io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel value) {
    value.getClass();
  if (bookingChannel_ != null &&
        bookingChannel_ != io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel.getDefaultInstance()) {
      bookingChannel_ =
        io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel.newBuilder(bookingChannel_).mergeFrom(value).buildPartial();
    } else {
      bookingChannel_ = value;
    }
    
  }
  /**
   * <pre>
   * Booking channel. Obligatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
   */
  private void clearBookingChannel() {  bookingChannel_ = null;
    
  }

  public static final int EXTRANETUSER_FIELD_NUMBER = 3;
  private io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser_;
  /**
   * <pre>
   * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
   */
  @java.lang.Override
  public boolean hasExtranetUser() {
    return extranetUser_ != null;
  }
  /**
   * <pre>
   * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser getExtranetUser() {
    return extranetUser_ == null ? io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser.getDefaultInstance() : extranetUser_;
  }
  /**
   * <pre>
   * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
   */
  private void setExtranetUser(io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser value) {
    value.getClass();
  extranetUser_ = value;
    
    }
  /**
   * <pre>
   * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeExtranetUser(io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser value) {
    value.getClass();
  if (extranetUser_ != null &&
        extranetUser_ != io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser.getDefaultInstance()) {
      extranetUser_ =
        io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser.newBuilder(extranetUser_).mergeFrom(value).buildPartial();
    } else {
      extranetUser_ = value;
    }
    
  }
  /**
   * <pre>
   * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
   */
  private void clearExtranetUser() {  extranetUser_ = null;
    
  }

  public static final int BOOKINGAGENT_FIELD_NUMBER = 4;
  private io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent_;
  /**
   * <pre>
   * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
   */
  @java.lang.Override
  public boolean hasBookingAgent() {
    return bookingAgent_ != null;
  }
  /**
   * <pre>
   * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent getBookingAgent() {
    return bookingAgent_ == null ? io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent.getDefaultInstance() : bookingAgent_;
  }
  /**
   * <pre>
   * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
   */
  private void setBookingAgent(io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent value) {
    value.getClass();
  bookingAgent_ = value;
    
    }
  /**
   * <pre>
   * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeBookingAgent(io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent value) {
    value.getClass();
  if (bookingAgent_ != null &&
        bookingAgent_ != io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent.getDefaultInstance()) {
      bookingAgent_ =
        io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent.newBuilder(bookingAgent_).mergeFrom(value).buildPartial();
    } else {
      bookingAgent_ = value;
    }
    
  }
  /**
   * <pre>
   * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
   */
  private void clearBookingAgent() {  bookingAgent_ = null;
    
  }

  public static final int MARKETPLACEVENDOR_FIELD_NUMBER = 5;
  private io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor_;
  /**
   * <pre>
   * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
   */
  @java.lang.Override
  public boolean hasMarketplaceVendor() {
    return marketplaceVendor_ != null;
  }
  /**
   * <pre>
   * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor getMarketplaceVendor() {
    return marketplaceVendor_ == null ? io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor.getDefaultInstance() : marketplaceVendor_;
  }
  /**
   * <pre>
   * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
   */
  private void setMarketplaceVendor(io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor value) {
    value.getClass();
  marketplaceVendor_ = value;
    
    }
  /**
   * <pre>
   * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeMarketplaceVendor(io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor value) {
    value.getClass();
  if (marketplaceVendor_ != null &&
        marketplaceVendor_ != io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor.getDefaultInstance()) {
      marketplaceVendor_ =
        io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor.newBuilder(marketplaceVendor_).mergeFrom(value).buildPartial();
    } else {
      marketplaceVendor_ = value;
    }
    
  }
  /**
   * <pre>
   * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
   */
  private void clearMarketplaceVendor() {  marketplaceVendor_ = null;
    
  }

  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSource parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.BookingSource prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Booking source used in booking
   * </pre>
   *
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.BookingSource}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.BookingSource, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.BookingSource)
      io.bokun.inventory.common.api.grpc.BookingSourceOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.BookingSource.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Booking sales segment. Mandatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
     * @return The enum numeric value on the wire for segment.
     */
    @java.lang.Override
    public int getSegmentValue() {
      return instance.getSegmentValue();
    }
    /**
     * <pre>
     * Booking sales segment. Mandatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
     * @param value The segment to set.
     * @return This builder for chaining.
     */
    public Builder setSegmentValue(int value) {
      copyOnWrite();
      instance.setSegmentValue(value);
      return this;
    }
    /**
     * <pre>
     * Booking sales segment. Mandatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
     * @return The segment.
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.SalesSegment getSegment() {
      return instance.getSegment();
    }
    /**
     * <pre>
     * Booking sales segment. Mandatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
     * @param value The enum numeric value on the wire for segment to set.
     * @return This builder for chaining.
     */
    public Builder setSegment(io.bokun.inventory.common.api.grpc.SalesSegment value) {
      copyOnWrite();
      instance.setSegment(value);
      return this;
    }
    /**
     * <pre>
     * Booking sales segment. Mandatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.SalesSegment segment = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSegment() {
      copyOnWrite();
      instance.clearSegment();
      return this;
    }

    /**
     * <pre>
     * Booking channel. Obligatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
     */
    @java.lang.Override
    public boolean hasBookingChannel() {
      return instance.hasBookingChannel();
    }
    /**
     * <pre>
     * Booking channel. Obligatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel getBookingChannel() {
      return instance.getBookingChannel();
    }
    /**
     * <pre>
     * Booking channel. Obligatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
     */
    public Builder setBookingChannel(io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel value) {
      copyOnWrite();
      instance.setBookingChannel(value);
      return this;
      }
    /**
     * <pre>
     * Booking channel. Obligatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
     */
    public Builder setBookingChannel(
        io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel.Builder builderForValue) {
      copyOnWrite();
      instance.setBookingChannel(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Booking channel. Obligatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
     */
    public Builder mergeBookingChannel(io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel value) {
      copyOnWrite();
      instance.mergeBookingChannel(value);
      return this;
    }
    /**
     * <pre>
     * Booking channel. Obligatory
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingChannel bookingChannel = 2;</code>
     */
    public Builder clearBookingChannel() {  copyOnWrite();
      instance.clearBookingChannel();
      return this;
    }

    /**
     * <pre>
     * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
     */
    @java.lang.Override
    public boolean hasExtranetUser() {
      return instance.hasExtranetUser();
    }
    /**
     * <pre>
     * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser getExtranetUser() {
      return instance.getExtranetUser();
    }
    /**
     * <pre>
     * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
     */
    public Builder setExtranetUser(io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser value) {
      copyOnWrite();
      instance.setExtranetUser(value);
      return this;
      }
    /**
     * <pre>
     * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
     */
    public Builder setExtranetUser(
        io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser.Builder builderForValue) {
      copyOnWrite();
      instance.setExtranetUser(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
     */
    public Builder mergeExtranetUser(io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser value) {
      copyOnWrite();
      instance.mergeExtranetUser(value);
      return this;
    }
    /**
     * <pre>
     * Extranet user who made the booking. Optional. Filled when SalesSegment is DIRECT_OFFLINE
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceExtranetUser extranetUser = 3;</code>
     */
    public Builder clearExtranetUser() {  copyOnWrite();
      instance.clearExtranetUser();
      return this;
    }

    /**
     * <pre>
     * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
     */
    @java.lang.Override
    public boolean hasBookingAgent() {
      return instance.hasBookingAgent();
    }
    /**
     * <pre>
     * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent getBookingAgent() {
      return instance.getBookingAgent();
    }
    /**
     * <pre>
     * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
     */
    public Builder setBookingAgent(io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent value) {
      copyOnWrite();
      instance.setBookingAgent(value);
      return this;
      }
    /**
     * <pre>
     * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
     */
    public Builder setBookingAgent(
        io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent.Builder builderForValue) {
      copyOnWrite();
      instance.setBookingAgent(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
     */
    public Builder mergeBookingAgent(io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent value) {
      copyOnWrite();
      instance.mergeBookingAgent(value);
      return this;
    }
    /**
     * <pre>
     * Agent who did the booking. Optional. Filled when SalesSegment is AGENT_AREA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent bookingAgent = 4;</code>
     */
    public Builder clearBookingAgent() {  copyOnWrite();
      instance.clearBookingAgent();
      return this;
    }

    /**
     * <pre>
     * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
     */
    @java.lang.Override
    public boolean hasMarketplaceVendor() {
      return instance.hasMarketplaceVendor();
    }
    /**
     * <pre>
     * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor getMarketplaceVendor() {
      return instance.getMarketplaceVendor();
    }
    /**
     * <pre>
     * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
     */
    public Builder setMarketplaceVendor(io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor value) {
      copyOnWrite();
      instance.setMarketplaceVendor(value);
      return this;
      }
    /**
     * <pre>
     * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
     */
    public Builder setMarketplaceVendor(
        io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor.Builder builderForValue) {
      copyOnWrite();
      instance.setMarketplaceVendor(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
     */
    public Builder mergeMarketplaceVendor(io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor value) {
      copyOnWrite();
      instance.mergeMarketplaceVendor(value);
      return this;
    }
    /**
     * <pre>
     * Marketplace reseller who resold booking. Optional. Filled when SalesSegment is MARKETPLACE or OTA
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.BookingSourceMarketplaceVendor marketplaceVendor = 5;</code>
     */
    public Builder clearMarketplaceVendor() {  copyOnWrite();
      instance.clearMarketplaceVendor();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.BookingSource)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.BookingSource();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "segment_",
            "bookingChannel_",
            "extranetUser_",
            "bookingAgent_",
            "marketplaceVendor_",
          };
          java.lang.String info =
              "\u0000\u0005\u0000\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\f\u0002\t\u0003" +
              "\t\u0004\t\u0005\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.BookingSource> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.BookingSource.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.BookingSource>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.BookingSource)
  private static final io.bokun.inventory.common.api.grpc.BookingSource DEFAULT_INSTANCE;
  static {
    BookingSource defaultInstance = new BookingSource();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BookingSource.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.BookingSource getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BookingSource> PARSER;

  public static com.google.protobuf.Parser<BookingSource> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

