// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * <pre>
 * Booking agent used in Booking.bookingSource
 * </pre>
 *
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent}
 */
public  final class BookingSourceBookingAgent extends
    com.google.protobuf.GeneratedMessageLite<
        BookingSourceBookingAgent, BookingSourceBookingAgent.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent)
    BookingSourceBookingAgentOrBuilder {
  private BookingSourceBookingAgent() {
    id_ = "";
    title_ = "";
    companyRegistrationNumber_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <pre>
   * agent id. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <pre>
   * agent id. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <pre>
   * agent id. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <pre>
   * agent id. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <pre>
   * agent id. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private java.lang.String title_;
  /**
   * <pre>
   * Title. Mandatory
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <pre>
   * Title. Mandatory
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <pre>
   * Title. Mandatory
   * </pre>
   *
   * <code>string title = 2;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    title_ = value;
  }
  /**
   * <pre>
   * Title. Mandatory
   * </pre>
   *
   * <code>string title = 2;</code>
   */
  private void clearTitle() {
    
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <pre>
   * Title. Mandatory
   * </pre>
   *
   * <code>string title = 2;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();
    
  }

  public static final int COMPANYREGISTRATIONNUMBER_FIELD_NUMBER = 3;
  private java.lang.String companyRegistrationNumber_;
  /**
   * <pre>
   * Agent company registration number. Optional
   * </pre>
   *
   * <code>string companyRegistrationNumber = 3;</code>
   * @return The companyRegistrationNumber.
   */
  @java.lang.Override
  public java.lang.String getCompanyRegistrationNumber() {
    return companyRegistrationNumber_;
  }
  /**
   * <pre>
   * Agent company registration number. Optional
   * </pre>
   *
   * <code>string companyRegistrationNumber = 3;</code>
   * @return The bytes for companyRegistrationNumber.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCompanyRegistrationNumberBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(companyRegistrationNumber_);
  }
  /**
   * <pre>
   * Agent company registration number. Optional
   * </pre>
   *
   * <code>string companyRegistrationNumber = 3;</code>
   * @param value The companyRegistrationNumber to set.
   */
  private void setCompanyRegistrationNumber(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    companyRegistrationNumber_ = value;
  }
  /**
   * <pre>
   * Agent company registration number. Optional
   * </pre>
   *
   * <code>string companyRegistrationNumber = 3;</code>
   */
  private void clearCompanyRegistrationNumber() {
    
    companyRegistrationNumber_ = getDefaultInstance().getCompanyRegistrationNumber();
  }
  /**
   * <pre>
   * Agent company registration number. Optional
   * </pre>
   *
   * <code>string companyRegistrationNumber = 3;</code>
   * @param value The bytes for companyRegistrationNumber to set.
   */
  private void setCompanyRegistrationNumberBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    companyRegistrationNumber_ = value.toStringUtf8();
    
  }

  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Booking agent used in Booking.bookingSource
   * </pre>
   *
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent)
      io.bokun.inventory.common.api.grpc.BookingSourceBookingAgentOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * agent id. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <pre>
     * agent id. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <pre>
     * agent id. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <pre>
     * agent id. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <pre>
     * agent id. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Title. Mandatory
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <pre>
     * Title. Mandatory
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <pre>
     * Title. Mandatory
     * </pre>
     *
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <pre>
     * Title. Mandatory
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <pre>
     * Title. Mandatory
     * </pre>
     *
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <pre>
     * Agent company registration number. Optional
     * </pre>
     *
     * <code>string companyRegistrationNumber = 3;</code>
     * @return The companyRegistrationNumber.
     */
    @java.lang.Override
    public java.lang.String getCompanyRegistrationNumber() {
      return instance.getCompanyRegistrationNumber();
    }
    /**
     * <pre>
     * Agent company registration number. Optional
     * </pre>
     *
     * <code>string companyRegistrationNumber = 3;</code>
     * @return The bytes for companyRegistrationNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCompanyRegistrationNumberBytes() {
      return instance.getCompanyRegistrationNumberBytes();
    }
    /**
     * <pre>
     * Agent company registration number. Optional
     * </pre>
     *
     * <code>string companyRegistrationNumber = 3;</code>
     * @param value The companyRegistrationNumber to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyRegistrationNumber(
        java.lang.String value) {
      copyOnWrite();
      instance.setCompanyRegistrationNumber(value);
      return this;
    }
    /**
     * <pre>
     * Agent company registration number. Optional
     * </pre>
     *
     * <code>string companyRegistrationNumber = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearCompanyRegistrationNumber() {
      copyOnWrite();
      instance.clearCompanyRegistrationNumber();
      return this;
    }
    /**
     * <pre>
     * Agent company registration number. Optional
     * </pre>
     *
     * <code>string companyRegistrationNumber = 3;</code>
     * @param value The bytes for companyRegistrationNumber to set.
     * @return This builder for chaining.
     */
    public Builder setCompanyRegistrationNumberBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCompanyRegistrationNumberBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "title_",
            "companyRegistrationNumber_",
          };
          java.lang.String info =
              "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent)
  private static final io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent DEFAULT_INSTANCE;
  static {
    BookingSourceBookingAgent defaultInstance = new BookingSourceBookingAgent();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      BookingSourceBookingAgent.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.BookingSourceBookingAgent getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<BookingSourceBookingAgent> PARSER;

  public static com.google.protobuf.Parser<BookingSourceBookingAgent> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

