// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.CancelReservationResponse}
 */
public  final class CancelReservationResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CancelReservationResponse, CancelReservationResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.CancelReservationResponse)
    CancelReservationResponseOrBuilder {
  private CancelReservationResponse() {
  }
  private int cancelReservationResultCase_ = 0;
  private java.lang.Object cancelReservationResult_;
  public enum CancelReservationResultCase {
    SUCCESSFULRESERVATIONCANCELLATION(1),
    FAILEDRESERVATIONCANCELLATION(2),
    CANCELRESERVATIONRESULT_NOT_SET(0);
    private final int value;
    private CancelReservationResultCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static CancelReservationResultCase valueOf(int value) {
      return forNumber(value);
    }

    public static CancelReservationResultCase forNumber(int value) {
      switch (value) {
        case 1: return SUCCESSFULRESERVATIONCANCELLATION;
        case 2: return FAILEDRESERVATIONCANCELLATION;
        case 0: return CANCELRESERVATIONRESULT_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public CancelReservationResultCase
  getCancelReservationResultCase() {
    return CancelReservationResultCase.forNumber(
        cancelReservationResultCase_);
  }

  private void clearCancelReservationResult() {
    cancelReservationResultCase_ = 0;
    cancelReservationResult_ = null;
  }

  public static final int SUCCESSFULRESERVATIONCANCELLATION_FIELD_NUMBER = 1;
  /**
   * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
   */
  @java.lang.Override
  public boolean hasSuccessfulReservationCancellation() {
    return cancelReservationResultCase_ == 1;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation getSuccessfulReservationCancellation() {
    if (cancelReservationResultCase_ == 1) {
       return (io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation) cancelReservationResult_;
    }
    return io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation.getDefaultInstance();
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
   */
  private void setSuccessfulReservationCancellation(io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation value) {
    value.getClass();
  cancelReservationResult_ = value;
    cancelReservationResultCase_ = 1;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
   */
  private void mergeSuccessfulReservationCancellation(io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation value) {
    value.getClass();
  if (cancelReservationResultCase_ == 1 &&
        cancelReservationResult_ != io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation.getDefaultInstance()) {
      cancelReservationResult_ = io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation.newBuilder((io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation) cancelReservationResult_)
          .mergeFrom(value).buildPartial();
    } else {
      cancelReservationResult_ = value;
    }
    cancelReservationResultCase_ = 1;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
   */
  private void clearSuccessfulReservationCancellation() {
    if (cancelReservationResultCase_ == 1) {
      cancelReservationResultCase_ = 0;
      cancelReservationResult_ = null;
    }
  }

  public static final int FAILEDRESERVATIONCANCELLATION_FIELD_NUMBER = 2;
  /**
   * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
   */
  @java.lang.Override
  public boolean hasFailedReservationCancellation() {
    return cancelReservationResultCase_ == 2;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.FailedReservationCancellation getFailedReservationCancellation() {
    if (cancelReservationResultCase_ == 2) {
       return (io.bokun.inventory.common.api.grpc.FailedReservationCancellation) cancelReservationResult_;
    }
    return io.bokun.inventory.common.api.grpc.FailedReservationCancellation.getDefaultInstance();
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
   */
  private void setFailedReservationCancellation(io.bokun.inventory.common.api.grpc.FailedReservationCancellation value) {
    value.getClass();
  cancelReservationResult_ = value;
    cancelReservationResultCase_ = 2;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
   */
  private void mergeFailedReservationCancellation(io.bokun.inventory.common.api.grpc.FailedReservationCancellation value) {
    value.getClass();
  if (cancelReservationResultCase_ == 2 &&
        cancelReservationResult_ != io.bokun.inventory.common.api.grpc.FailedReservationCancellation.getDefaultInstance()) {
      cancelReservationResult_ = io.bokun.inventory.common.api.grpc.FailedReservationCancellation.newBuilder((io.bokun.inventory.common.api.grpc.FailedReservationCancellation) cancelReservationResult_)
          .mergeFrom(value).buildPartial();
    } else {
      cancelReservationResult_ = value;
    }
    cancelReservationResultCase_ = 2;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
   */
  private void clearFailedReservationCancellation() {
    if (cancelReservationResultCase_ == 2) {
      cancelReservationResultCase_ = 0;
      cancelReservationResult_ = null;
    }
  }

  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.CancelReservationResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.CancelReservationResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.CancelReservationResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.CancelReservationResponse)
      io.bokun.inventory.common.api.grpc.CancelReservationResponseOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.CancelReservationResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public CancelReservationResultCase
        getCancelReservationResultCase() {
      return instance.getCancelReservationResultCase();
    }

    public Builder clearCancelReservationResult() {
      copyOnWrite();
      instance.clearCancelReservationResult();
      return this;
    }


    /**
     * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
     */
    @java.lang.Override
    public boolean hasSuccessfulReservationCancellation() {
      return instance.hasSuccessfulReservationCancellation();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation getSuccessfulReservationCancellation() {
      return instance.getSuccessfulReservationCancellation();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
     */
    public Builder setSuccessfulReservationCancellation(io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation value) {
      copyOnWrite();
      instance.setSuccessfulReservationCancellation(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
     */
    public Builder setSuccessfulReservationCancellation(
        io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation.Builder builderForValue) {
      copyOnWrite();
      instance.setSuccessfulReservationCancellation(builderForValue.build());
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
     */
    public Builder mergeSuccessfulReservationCancellation(io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation value) {
      copyOnWrite();
      instance.mergeSuccessfulReservationCancellation(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation successfulReservationCancellation = 1;</code>
     */
    public Builder clearSuccessfulReservationCancellation() {
      copyOnWrite();
      instance.clearSuccessfulReservationCancellation();
      return this;
    }

    /**
     * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
     */
    @java.lang.Override
    public boolean hasFailedReservationCancellation() {
      return instance.hasFailedReservationCancellation();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.FailedReservationCancellation getFailedReservationCancellation() {
      return instance.getFailedReservationCancellation();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
     */
    public Builder setFailedReservationCancellation(io.bokun.inventory.common.api.grpc.FailedReservationCancellation value) {
      copyOnWrite();
      instance.setFailedReservationCancellation(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
     */
    public Builder setFailedReservationCancellation(
        io.bokun.inventory.common.api.grpc.FailedReservationCancellation.Builder builderForValue) {
      copyOnWrite();
      instance.setFailedReservationCancellation(builderForValue.build());
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
     */
    public Builder mergeFailedReservationCancellation(io.bokun.inventory.common.api.grpc.FailedReservationCancellation value) {
      copyOnWrite();
      instance.mergeFailedReservationCancellation(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.FailedReservationCancellation failedReservationCancellation = 2;</code>
     */
    public Builder clearFailedReservationCancellation() {
      copyOnWrite();
      instance.clearFailedReservationCancellation();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.CancelReservationResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.CancelReservationResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "cancelReservationResult_",
            "cancelReservationResultCase_",
            io.bokun.inventory.common.api.grpc.SuccessfulReservationCancellation.class,
            io.bokun.inventory.common.api.grpc.FailedReservationCancellation.class,
          };
          java.lang.String info =
              "\u0000\u0002\u0001\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001<\u0000\u0002<" +
              "\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.CancelReservationResponse> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.CancelReservationResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.CancelReservationResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.CancelReservationResponse)
  private static final io.bokun.inventory.common.api.grpc.CancelReservationResponse DEFAULT_INSTANCE;
  static {
    CancelReservationResponse defaultInstance = new CancelReservationResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CancelReservationResponse.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.CancelReservationResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CancelReservationResponse> PARSER;

  public static com.google.protobuf.Parser<CancelReservationResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

