// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface ConfirmBookingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.ConfirmBookingResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.io.bokun.inventory.common.api.grpc.SuccessfulBooking successfulBooking = 1;</code>
   * @return Whether the successfulBooking field is set.
   */
  boolean hasSuccessfulBooking();
  /**
   * <code>.io.bokun.inventory.common.api.grpc.SuccessfulBooking successfulBooking = 1;</code>
   * @return The successfulBooking.
   */
  io.bokun.inventory.common.api.grpc.SuccessfulBooking getSuccessfulBooking();

  /**
   * <code>.io.bokun.inventory.common.api.grpc.FailedBooking failedBooking = 2;</code>
   * @return Whether the failedBooking field is set.
   */
  boolean hasFailedBooking();
  /**
   * <code>.io.bokun.inventory.common.api.grpc.FailedBooking failedBooking = 2;</code>
   * @return The failedBooking.
   */
  io.bokun.inventory.common.api.grpc.FailedBooking getFailedBooking();

  public io.bokun.inventory.common.api.grpc.ConfirmBookingResponse.BookingResultCase getBookingResultCase();
}
