// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface DateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.Date)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>int32 year = 1;</code>
   * @return The year.
   */
  int getYear();

  /**
   * <code>int32 month = 2;</code>
   * @return The month.
   */
  int getMonth();

  /**
   * <code>int32 day = 3;</code>
   * @return The day.
   */
  int getDay();
}
