// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * <pre>
 * All fields mandatory; should at least be set to 0.
 * </pre>
 *
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.Duration}
 */
public  final class Duration extends
    com.google.protobuf.GeneratedMessageLite<
        Duration, Duration.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.Duration)
    DurationOrBuilder {
  private Duration() {
  }
  public static final int MINUTES_FIELD_NUMBER = 1;
  private int minutes_;
  /**
   * <code>int32 minutes = 1;</code>
   * @return The minutes.
   */
  @java.lang.Override
  public int getMinutes() {
    return minutes_;
  }
  /**
   * <code>int32 minutes = 1;</code>
   * @param value The minutes to set.
   */
  private void setMinutes(int value) {
    
    minutes_ = value;
  }
  /**
   * <code>int32 minutes = 1;</code>
   */
  private void clearMinutes() {
    
    minutes_ = 0;
  }

  public static final int HOURS_FIELD_NUMBER = 2;
  private int hours_;
  /**
   * <code>int32 hours = 2;</code>
   * @return The hours.
   */
  @java.lang.Override
  public int getHours() {
    return hours_;
  }
  /**
   * <code>int32 hours = 2;</code>
   * @param value The hours to set.
   */
  private void setHours(int value) {
    
    hours_ = value;
  }
  /**
   * <code>int32 hours = 2;</code>
   */
  private void clearHours() {
    
    hours_ = 0;
  }

  public static final int DAYS_FIELD_NUMBER = 3;
  private int days_;
  /**
   * <code>int32 days = 3;</code>
   * @return The days.
   */
  @java.lang.Override
  public int getDays() {
    return days_;
  }
  /**
   * <code>int32 days = 3;</code>
   * @param value The days to set.
   */
  private void setDays(int value) {
    
    days_ = value;
  }
  /**
   * <code>int32 days = 3;</code>
   */
  private void clearDays() {
    
    days_ = 0;
  }

  public static final int WEEKS_FIELD_NUMBER = 4;
  private int weeks_;
  /**
   * <code>int32 weeks = 4;</code>
   * @return The weeks.
   */
  @java.lang.Override
  public int getWeeks() {
    return weeks_;
  }
  /**
   * <code>int32 weeks = 4;</code>
   * @param value The weeks to set.
   */
  private void setWeeks(int value) {
    
    weeks_ = value;
  }
  /**
   * <code>int32 weeks = 4;</code>
   */
  private void clearWeeks() {
    
    weeks_ = 0;
  }

  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Duration parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.Duration prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * All fields mandatory; should at least be set to 0.
   * </pre>
   *
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.Duration}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.Duration, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.Duration)
      io.bokun.inventory.common.api.grpc.DurationOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.Duration.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 minutes = 1;</code>
     * @return The minutes.
     */
    @java.lang.Override
    public int getMinutes() {
      return instance.getMinutes();
    }
    /**
     * <code>int32 minutes = 1;</code>
     * @param value The minutes to set.
     * @return This builder for chaining.
     */
    public Builder setMinutes(int value) {
      copyOnWrite();
      instance.setMinutes(value);
      return this;
    }
    /**
     * <code>int32 minutes = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinutes() {
      copyOnWrite();
      instance.clearMinutes();
      return this;
    }

    /**
     * <code>int32 hours = 2;</code>
     * @return The hours.
     */
    @java.lang.Override
    public int getHours() {
      return instance.getHours();
    }
    /**
     * <code>int32 hours = 2;</code>
     * @param value The hours to set.
     * @return This builder for chaining.
     */
    public Builder setHours(int value) {
      copyOnWrite();
      instance.setHours(value);
      return this;
    }
    /**
     * <code>int32 hours = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearHours() {
      copyOnWrite();
      instance.clearHours();
      return this;
    }

    /**
     * <code>int32 days = 3;</code>
     * @return The days.
     */
    @java.lang.Override
    public int getDays() {
      return instance.getDays();
    }
    /**
     * <code>int32 days = 3;</code>
     * @param value The days to set.
     * @return This builder for chaining.
     */
    public Builder setDays(int value) {
      copyOnWrite();
      instance.setDays(value);
      return this;
    }
    /**
     * <code>int32 days = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDays() {
      copyOnWrite();
      instance.clearDays();
      return this;
    }

    /**
     * <code>int32 weeks = 4;</code>
     * @return The weeks.
     */
    @java.lang.Override
    public int getWeeks() {
      return instance.getWeeks();
    }
    /**
     * <code>int32 weeks = 4;</code>
     * @param value The weeks to set.
     * @return This builder for chaining.
     */
    public Builder setWeeks(int value) {
      copyOnWrite();
      instance.setWeeks(value);
      return this;
    }
    /**
     * <code>int32 weeks = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearWeeks() {
      copyOnWrite();
      instance.clearWeeks();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.Duration)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.Duration();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "minutes_",
            "hours_",
            "days_",
            "weeks_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
              "\u0003\u0004\u0004\u0004";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.Duration> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.Duration.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.Duration>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.Duration)
  private static final io.bokun.inventory.common.api.grpc.Duration DEFAULT_INSTANCE;
  static {
    Duration defaultInstance = new Duration();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Duration.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.Duration getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Duration> PARSER;

  public static com.google.protobuf.Parser<Duration> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

