// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface ExtraBookingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.ExtraBooking)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Id of extra. Mandatory
   * </pre>
   *
   * <code>string extraId = 1;</code>
   * @return The extraId.
   */
  java.lang.String getExtraId();
  /**
   * <pre>
   * Id of extra. Mandatory
   * </pre>
   *
   * <code>string extraId = 1;</code>
   * @return The bytes for extraId.
   */
  com.google.protobuf.ByteString
      getExtraIdBytes();

  /**
   * <pre>
   * Amount. Mandatory
   * </pre>
   *
   * <code>int32 amount = 2;</code>
   * @return The amount.
   */
  int getAmount();

  /**
   * <pre>
   * Extra per person or extra per booking?. Mandatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.ExtraPricingType pricingType = 3;</code>
   * @return The enum numeric value on the wire for pricingType.
   */
  int getPricingTypeValue();
  /**
   * <pre>
   * Extra per person or extra per booking?. Mandatory
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.ExtraPricingType pricingType = 3;</code>
   * @return The pricingType.
   */
  io.bokun.inventory.common.api.grpc.ExtraPricingType getPricingType();

  /**
   * <pre>
   * Amount and currency. Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Price price = 4;</code>
   * @return Whether the price field is set.
   */
  boolean hasPrice();
  /**
   * <pre>
   * Amount and currency. Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Price price = 4;</code>
   * @return The price.
   */
  io.bokun.inventory.common.api.grpc.Price getPrice();
}
