// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface ExtraOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.Extra)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Id of extra on external (non-Bokun) platform. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <pre>
   * Id of extra on external (non-Bokun) platform. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <pre>
   * Title of extra. Mandatory.
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <pre>
   * Title of extra. Mandatory.
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <pre>
   * Description of extra. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Description of extra. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * If true, extra is optional for product. Mandatory
   * </pre>
   *
   * <code>bool optional = 4;</code>
   * @return The optional.
   */
  boolean getOptional();

  /**
   * <pre>
   * How many extras can be acquired per single booking. Optional
   * </pre>
   *
   * <code>int32 maxPerBooking = 6;</code>
   * @return The maxPerBooking.
   */
  int getMaxPerBooking();

  /**
   * <pre>
   * If true, max one item can be acquired by each passenger/activity actor/etc. Optional
   * </pre>
   *
   * <code>bool limitByPax = 7;</code>
   * @return The limitByPax.
   */
  boolean getLimitByPax();

  /**
   * <pre>
   *If true, this may increase capacity for a product. Optional.
   * </pre>
   *
   * <code>bool increasesCapacity = 8;</code>
   * @return The increasesCapacity.
   */
  boolean getIncreasesCapacity();
}
