// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * <pre>
 * Extra available for certain product
 * </pre>
 *
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.Extra}
 */
public  final class Extra extends
    com.google.protobuf.GeneratedMessageLite<
        Extra, Extra.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.Extra)
    ExtraOrBuilder {
  private Extra() {
    id_ = "";
    title_ = "";
    description_ = "";
  }
  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <pre>
   * Id of extra on external (non-Bokun) platform. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <pre>
   * Id of extra on external (non-Bokun) platform. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <pre>
   * Id of extra on external (non-Bokun) platform. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <pre>
   * Id of extra on external (non-Bokun) platform. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <pre>
   * Id of extra on external (non-Bokun) platform. Mandatory
   * </pre>
   *
   * <code>string id = 1;</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  private java.lang.String title_;
  /**
   * <pre>
   * Title of extra. Mandatory.
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <pre>
   * Title of extra. Mandatory.
   * </pre>
   *
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <pre>
   * Title of extra. Mandatory.
   * </pre>
   *
   * <code>string title = 2;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    title_ = value;
  }
  /**
   * <pre>
   * Title of extra. Mandatory.
   * </pre>
   *
   * <code>string title = 2;</code>
   */
  private void clearTitle() {
    
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <pre>
   * Title of extra. Mandatory.
   * </pre>
   *
   * <code>string title = 2;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();
    
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 3;
  private java.lang.String description_;
  /**
   * <pre>
   * Description of extra. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <pre>
   * Description of extra. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <pre>
   * Description of extra. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <pre>
   * Description of extra. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   */
  private void clearDescription() {
    
    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <pre>
   * Description of extra. Optional.
   * </pre>
   *
   * <code>string description = 3;</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();
    
  }

  public static final int OPTIONAL_FIELD_NUMBER = 4;
  private boolean optional_;
  /**
   * <pre>
   * If true, extra is optional for product. Mandatory
   * </pre>
   *
   * <code>bool optional = 4;</code>
   * @return The optional.
   */
  @java.lang.Override
  public boolean getOptional() {
    return optional_;
  }
  /**
   * <pre>
   * If true, extra is optional for product. Mandatory
   * </pre>
   *
   * <code>bool optional = 4;</code>
   * @param value The optional to set.
   */
  private void setOptional(boolean value) {
    
    optional_ = value;
  }
  /**
   * <pre>
   * If true, extra is optional for product. Mandatory
   * </pre>
   *
   * <code>bool optional = 4;</code>
   */
  private void clearOptional() {
    
    optional_ = false;
  }

  public static final int MAXPERBOOKING_FIELD_NUMBER = 6;
  private int maxPerBooking_;
  /**
   * <pre>
   * How many extras can be acquired per single booking. Optional
   * </pre>
   *
   * <code>int32 maxPerBooking = 6;</code>
   * @return The maxPerBooking.
   */
  @java.lang.Override
  public int getMaxPerBooking() {
    return maxPerBooking_;
  }
  /**
   * <pre>
   * How many extras can be acquired per single booking. Optional
   * </pre>
   *
   * <code>int32 maxPerBooking = 6;</code>
   * @param value The maxPerBooking to set.
   */
  private void setMaxPerBooking(int value) {
    
    maxPerBooking_ = value;
  }
  /**
   * <pre>
   * How many extras can be acquired per single booking. Optional
   * </pre>
   *
   * <code>int32 maxPerBooking = 6;</code>
   */
  private void clearMaxPerBooking() {
    
    maxPerBooking_ = 0;
  }

  public static final int LIMITBYPAX_FIELD_NUMBER = 7;
  private boolean limitByPax_;
  /**
   * <pre>
   * If true, max one item can be acquired by each passenger/activity actor/etc. Optional
   * </pre>
   *
   * <code>bool limitByPax = 7;</code>
   * @return The limitByPax.
   */
  @java.lang.Override
  public boolean getLimitByPax() {
    return limitByPax_;
  }
  /**
   * <pre>
   * If true, max one item can be acquired by each passenger/activity actor/etc. Optional
   * </pre>
   *
   * <code>bool limitByPax = 7;</code>
   * @param value The limitByPax to set.
   */
  private void setLimitByPax(boolean value) {
    
    limitByPax_ = value;
  }
  /**
   * <pre>
   * If true, max one item can be acquired by each passenger/activity actor/etc. Optional
   * </pre>
   *
   * <code>bool limitByPax = 7;</code>
   */
  private void clearLimitByPax() {
    
    limitByPax_ = false;
  }

  public static final int INCREASESCAPACITY_FIELD_NUMBER = 8;
  private boolean increasesCapacity_;
  /**
   * <pre>
   *If true, this may increase capacity for a product. Optional.
   * </pre>
   *
   * <code>bool increasesCapacity = 8;</code>
   * @return The increasesCapacity.
   */
  @java.lang.Override
  public boolean getIncreasesCapacity() {
    return increasesCapacity_;
  }
  /**
   * <pre>
   *If true, this may increase capacity for a product. Optional.
   * </pre>
   *
   * <code>bool increasesCapacity = 8;</code>
   * @param value The increasesCapacity to set.
   */
  private void setIncreasesCapacity(boolean value) {
    
    increasesCapacity_ = value;
  }
  /**
   * <pre>
   *If true, this may increase capacity for a product. Optional.
   * </pre>
   *
   * <code>bool increasesCapacity = 8;</code>
   */
  private void clearIncreasesCapacity() {
    
    increasesCapacity_ = false;
  }

  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Extra parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.Extra prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * Extra available for certain product
   * </pre>
   *
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.Extra}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.Extra, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.Extra)
      io.bokun.inventory.common.api.grpc.ExtraOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.Extra.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Id of extra on external (non-Bokun) platform. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <pre>
     * Id of extra on external (non-Bokun) platform. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <pre>
     * Id of extra on external (non-Bokun) platform. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <pre>
     * Id of extra on external (non-Bokun) platform. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <pre>
     * Id of extra on external (non-Bokun) platform. Mandatory
     * </pre>
     *
     * <code>string id = 1;</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <pre>
     * Title of extra. Mandatory.
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <pre>
     * Title of extra. Mandatory.
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <pre>
     * Title of extra. Mandatory.
     * </pre>
     *
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <pre>
     * Title of extra. Mandatory.
     * </pre>
     *
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <pre>
     * Title of extra. Mandatory.
     * </pre>
     *
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <pre>
     * Description of extra. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <pre>
     * Description of extra. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <pre>
     * Description of extra. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <pre>
     * Description of extra. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <pre>
     * Description of extra. Optional.
     * </pre>
     *
     * <code>string description = 3;</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <pre>
     * If true, extra is optional for product. Mandatory
     * </pre>
     *
     * <code>bool optional = 4;</code>
     * @return The optional.
     */
    @java.lang.Override
    public boolean getOptional() {
      return instance.getOptional();
    }
    /**
     * <pre>
     * If true, extra is optional for product. Mandatory
     * </pre>
     *
     * <code>bool optional = 4;</code>
     * @param value The optional to set.
     * @return This builder for chaining.
     */
    public Builder setOptional(boolean value) {
      copyOnWrite();
      instance.setOptional(value);
      return this;
    }
    /**
     * <pre>
     * If true, extra is optional for product. Mandatory
     * </pre>
     *
     * <code>bool optional = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearOptional() {
      copyOnWrite();
      instance.clearOptional();
      return this;
    }

    /**
     * <pre>
     * How many extras can be acquired per single booking. Optional
     * </pre>
     *
     * <code>int32 maxPerBooking = 6;</code>
     * @return The maxPerBooking.
     */
    @java.lang.Override
    public int getMaxPerBooking() {
      return instance.getMaxPerBooking();
    }
    /**
     * <pre>
     * How many extras can be acquired per single booking. Optional
     * </pre>
     *
     * <code>int32 maxPerBooking = 6;</code>
     * @param value The maxPerBooking to set.
     * @return This builder for chaining.
     */
    public Builder setMaxPerBooking(int value) {
      copyOnWrite();
      instance.setMaxPerBooking(value);
      return this;
    }
    /**
     * <pre>
     * How many extras can be acquired per single booking. Optional
     * </pre>
     *
     * <code>int32 maxPerBooking = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxPerBooking() {
      copyOnWrite();
      instance.clearMaxPerBooking();
      return this;
    }

    /**
     * <pre>
     * If true, max one item can be acquired by each passenger/activity actor/etc. Optional
     * </pre>
     *
     * <code>bool limitByPax = 7;</code>
     * @return The limitByPax.
     */
    @java.lang.Override
    public boolean getLimitByPax() {
      return instance.getLimitByPax();
    }
    /**
     * <pre>
     * If true, max one item can be acquired by each passenger/activity actor/etc. Optional
     * </pre>
     *
     * <code>bool limitByPax = 7;</code>
     * @param value The limitByPax to set.
     * @return This builder for chaining.
     */
    public Builder setLimitByPax(boolean value) {
      copyOnWrite();
      instance.setLimitByPax(value);
      return this;
    }
    /**
     * <pre>
     * If true, max one item can be acquired by each passenger/activity actor/etc. Optional
     * </pre>
     *
     * <code>bool limitByPax = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearLimitByPax() {
      copyOnWrite();
      instance.clearLimitByPax();
      return this;
    }

    /**
     * <pre>
     *If true, this may increase capacity for a product. Optional.
     * </pre>
     *
     * <code>bool increasesCapacity = 8;</code>
     * @return The increasesCapacity.
     */
    @java.lang.Override
    public boolean getIncreasesCapacity() {
      return instance.getIncreasesCapacity();
    }
    /**
     * <pre>
     *If true, this may increase capacity for a product. Optional.
     * </pre>
     *
     * <code>bool increasesCapacity = 8;</code>
     * @param value The increasesCapacity to set.
     * @return This builder for chaining.
     */
    public Builder setIncreasesCapacity(boolean value) {
      copyOnWrite();
      instance.setIncreasesCapacity(value);
      return this;
    }
    /**
     * <pre>
     *If true, this may increase capacity for a product. Optional.
     * </pre>
     *
     * <code>bool increasesCapacity = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearIncreasesCapacity() {
      copyOnWrite();
      instance.clearIncreasesCapacity();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.Extra)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.Extra();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "title_",
            "description_",
            "optional_",
            "maxPerBooking_",
            "limitByPax_",
            "increasesCapacity_",
          };
          java.lang.String info =
              "\u0000\u0007\u0000\u0000\u0001\b\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0208\u0004\u0007\u0006\u0004\u0007\u0007\b\u0007";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.Extra> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.Extra.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.Extra>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.Extra)
  private static final io.bokun.inventory.common.api.grpc.Extra DEFAULT_INSTANCE;
  static {
    Extra defaultInstance = new Extra();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Extra.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.Extra getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Extra> PARSER;

  public static com.google.protobuf.Parser<Extra> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

