// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.FailedReservation}
 */
public  final class FailedReservation extends
    com.google.protobuf.GeneratedMessageLite<
        FailedReservation, FailedReservation.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.FailedReservation)
    FailedReservationOrBuilder {
  private FailedReservation() {
    reservationError_ = "";
  }
  public static final int RESERVATIONERROR_FIELD_NUMBER = 1;
  private java.lang.String reservationError_;
  /**
   * <pre>
   * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
   * </pre>
   *
   * <code>string reservationError = 1;</code>
   * @return The reservationError.
   */
  @java.lang.Override
  public java.lang.String getReservationError() {
    return reservationError_;
  }
  /**
   * <pre>
   * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
   * </pre>
   *
   * <code>string reservationError = 1;</code>
   * @return The bytes for reservationError.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getReservationErrorBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(reservationError_);
  }
  /**
   * <pre>
   * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
   * </pre>
   *
   * <code>string reservationError = 1;</code>
   * @param value The reservationError to set.
   */
  private void setReservationError(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    reservationError_ = value;
  }
  /**
   * <pre>
   * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
   * </pre>
   *
   * <code>string reservationError = 1;</code>
   */
  private void clearReservationError() {
    
    reservationError_ = getDefaultInstance().getReservationError();
  }
  /**
   * <pre>
   * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
   * </pre>
   *
   * <code>string reservationError = 1;</code>
   * @param value The bytes for reservationError to set.
   */
  private void setReservationErrorBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    reservationError_ = value.toStringUtf8();
    
  }

  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.FailedReservation parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.FailedReservation prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.FailedReservation}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.FailedReservation, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.FailedReservation)
      io.bokun.inventory.common.api.grpc.FailedReservationOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.FailedReservation.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
     * </pre>
     *
     * <code>string reservationError = 1;</code>
     * @return The reservationError.
     */
    @java.lang.Override
    public java.lang.String getReservationError() {
      return instance.getReservationError();
    }
    /**
     * <pre>
     * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
     * </pre>
     *
     * <code>string reservationError = 1;</code>
     * @return The bytes for reservationError.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getReservationErrorBytes() {
      return instance.getReservationErrorBytes();
    }
    /**
     * <pre>
     * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
     * </pre>
     *
     * <code>string reservationError = 1;</code>
     * @param value The reservationError to set.
     * @return This builder for chaining.
     */
    public Builder setReservationError(
        java.lang.String value) {
      copyOnWrite();
      instance.setReservationError(value);
      return this;
    }
    /**
     * <pre>
     * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
     * </pre>
     *
     * <code>string reservationError = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReservationError() {
      copyOnWrite();
      instance.clearReservationError();
      return this;
    }
    /**
     * <pre>
     * Error message telling why this request has failed. Optional - remote end is not required to explicitly tell the reason of failure
     * </pre>
     *
     * <code>string reservationError = 1;</code>
     * @param value The bytes for reservationError to set.
     * @return This builder for chaining.
     */
    public Builder setReservationErrorBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setReservationErrorBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.FailedReservation)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.FailedReservation();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "reservationError_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.FailedReservation> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.FailedReservation.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.FailedReservation>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.FailedReservation)
  private static final io.bokun.inventory.common.api.grpc.FailedReservation DEFAULT_INSTANCE;
  static {
    FailedReservation defaultInstance = new FailedReservation();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      FailedReservation.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.FailedReservation getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<FailedReservation> PARSER;

  public static com.google.protobuf.Parser<FailedReservation> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

