// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.PickupDropoffPlace}
 */
public  final class PickupDropoffPlace extends
    com.google.protobuf.GeneratedMessageLite<
        PickupDropoffPlace, PickupDropoffPlace.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.PickupDropoffPlace)
    PickupDropoffPlaceOrBuilder {
  private PickupDropoffPlace() {
    title_ = "";
  }
  public static final int TITLE_FIELD_NUMBER = 1;
  private java.lang.String title_;
  /**
   * <pre>
   * Verbal description of pick up place. Mandatory.
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    return title_;
  }
  /**
   * <pre>
   * Verbal description of pick up place. Mandatory.
   * </pre>
   *
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(title_);
  }
  /**
   * <pre>
   * Verbal description of pick up place. Mandatory.
   * </pre>
   *
   * <code>string title = 1;</code>
   * @param value The title to set.
   */
  private void setTitle(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    title_ = value;
  }
  /**
   * <pre>
   * Verbal description of pick up place. Mandatory.
   * </pre>
   *
   * <code>string title = 1;</code>
   */
  private void clearTitle() {
    
    title_ = getDefaultInstance().getTitle();
  }
  /**
   * <pre>
   * Verbal description of pick up place. Mandatory.
   * </pre>
   *
   * <code>string title = 1;</code>
   * @param value The bytes for title to set.
   */
  private void setTitleBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    title_ = value.toStringUtf8();
    
  }

  public static final int ADDRESS_FIELD_NUMBER = 3;
  private io.bokun.inventory.common.api.grpc.Address address_;
  /**
   * <pre>
   * Precise location of pick up place. Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
   */
  @java.lang.Override
  public boolean hasAddress() {
    return address_ != null;
  }
  /**
   * <pre>
   * Precise location of pick up place. Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.Address getAddress() {
    return address_ == null ? io.bokun.inventory.common.api.grpc.Address.getDefaultInstance() : address_;
  }
  /**
   * <pre>
   * Precise location of pick up place. Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
   */
  private void setAddress(io.bokun.inventory.common.api.grpc.Address value) {
    value.getClass();
  address_ = value;
    
    }
  /**
   * <pre>
   * Precise location of pick up place. Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeAddress(io.bokun.inventory.common.api.grpc.Address value) {
    value.getClass();
  if (address_ != null &&
        address_ != io.bokun.inventory.common.api.grpc.Address.getDefaultInstance()) {
      address_ =
        io.bokun.inventory.common.api.grpc.Address.newBuilder(address_).mergeFrom(value).buildPartial();
    } else {
      address_ = value;
    }
    
  }
  /**
   * <pre>
   * Precise location of pick up place. Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
   */
  private void clearAddress() {  address_ = null;
    
  }

  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.PickupDropoffPlace prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.PickupDropoffPlace}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.PickupDropoffPlace, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.PickupDropoffPlace)
      io.bokun.inventory.common.api.grpc.PickupDropoffPlaceOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.PickupDropoffPlace.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * Verbal description of pick up place. Mandatory.
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return The title.
     */
    @java.lang.Override
    public java.lang.String getTitle() {
      return instance.getTitle();
    }
    /**
     * <pre>
     * Verbal description of pick up place. Mandatory.
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return The bytes for title.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      return instance.getTitleBytes();
    }
    /**
     * <pre>
     * Verbal description of pick up place. Mandatory.
     * </pre>
     *
     * <code>string title = 1;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      copyOnWrite();
      instance.setTitle(value);
      return this;
    }
    /**
     * <pre>
     * Verbal description of pick up place. Mandatory.
     * </pre>
     *
     * <code>string title = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      copyOnWrite();
      instance.clearTitle();
      return this;
    }
    /**
     * <pre>
     * Verbal description of pick up place. Mandatory.
     * </pre>
     *
     * <code>string title = 1;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTitleBytes(value);
      return this;
    }

    /**
     * <pre>
     * Precise location of pick up place. Mandatory.
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
     */
    @java.lang.Override
    public boolean hasAddress() {
      return instance.hasAddress();
    }
    /**
     * <pre>
     * Precise location of pick up place. Mandatory.
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.Address getAddress() {
      return instance.getAddress();
    }
    /**
     * <pre>
     * Precise location of pick up place. Mandatory.
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
     */
    public Builder setAddress(io.bokun.inventory.common.api.grpc.Address value) {
      copyOnWrite();
      instance.setAddress(value);
      return this;
      }
    /**
     * <pre>
     * Precise location of pick up place. Mandatory.
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
     */
    public Builder setAddress(
        io.bokun.inventory.common.api.grpc.Address.Builder builderForValue) {
      copyOnWrite();
      instance.setAddress(builderForValue.build());
      return this;
    }
    /**
     * <pre>
     * Precise location of pick up place. Mandatory.
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
     */
    public Builder mergeAddress(io.bokun.inventory.common.api.grpc.Address value) {
      copyOnWrite();
      instance.mergeAddress(value);
      return this;
    }
    /**
     * <pre>
     * Precise location of pick up place. Mandatory.
     * </pre>
     *
     * <code>.io.bokun.inventory.common.api.grpc.Address address = 3;</code>
     */
    public Builder clearAddress() {  copyOnWrite();
      instance.clearAddress();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.PickupDropoffPlace)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.PickupDropoffPlace();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "title_",
            "address_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0003\u0002\u0000\u0000\u0000\u0001\u0208\u0003\t" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.PickupDropoffPlace> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.PickupDropoffPlace.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.PickupDropoffPlace>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.PickupDropoffPlace)
  private static final io.bokun.inventory.common.api.grpc.PickupDropoffPlace DEFAULT_INSTANCE;
  static {
    PickupDropoffPlace defaultInstance = new PickupDropoffPlace();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PickupDropoffPlace.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.PickupDropoffPlace getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PickupDropoffPlace> PARSER;

  public static com.google.protobuf.Parser<PickupDropoffPlace> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

