// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface PricePerPersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.PricePerPerson)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice pricingCategoryWithPrice = 1;</code>
   */
  java.util.List<io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice> 
      getPricingCategoryWithPriceList();
  /**
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice pricingCategoryWithPrice = 1;</code>
   */
  io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice getPricingCategoryWithPrice(int index);
  /**
   * <code>repeated .io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice pricingCategoryWithPrice = 1;</code>
   */
  int getPricingCategoryWithPriceCount();
}
