// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice}
 */
public  final class PricingCategoryWithPrice extends
    com.google.protobuf.GeneratedMessageLite<
        PricingCategoryWithPrice, PricingCategoryWithPrice.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice)
    PricingCategoryWithPriceOrBuilder {
  private PricingCategoryWithPrice() {
    pricingCategoryId_ = "";
  }
  public static final int PRICINGCATEGORYID_FIELD_NUMBER = 1;
  private java.lang.String pricingCategoryId_;
  /**
   * <code>string pricingCategoryId = 1;</code>
   * @return The pricingCategoryId.
   */
  @java.lang.Override
  public java.lang.String getPricingCategoryId() {
    return pricingCategoryId_;
  }
  /**
   * <code>string pricingCategoryId = 1;</code>
   * @return The bytes for pricingCategoryId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getPricingCategoryIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(pricingCategoryId_);
  }
  /**
   * <code>string pricingCategoryId = 1;</code>
   * @param value The pricingCategoryId to set.
   */
  private void setPricingCategoryId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    pricingCategoryId_ = value;
  }
  /**
   * <code>string pricingCategoryId = 1;</code>
   */
  private void clearPricingCategoryId() {
    
    pricingCategoryId_ = getDefaultInstance().getPricingCategoryId();
  }
  /**
   * <code>string pricingCategoryId = 1;</code>
   * @param value The bytes for pricingCategoryId to set.
   */
  private void setPricingCategoryIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    pricingCategoryId_ = value.toStringUtf8();
    
  }

  public static final int PRICE_FIELD_NUMBER = 2;
  private io.bokun.inventory.common.api.grpc.Price price_;
  /**
   * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
   */
  @java.lang.Override
  public boolean hasPrice() {
    return price_ != null;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.Price getPrice() {
    return price_ == null ? io.bokun.inventory.common.api.grpc.Price.getDefaultInstance() : price_;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
   */
  private void setPrice(io.bokun.inventory.common.api.grpc.Price value) {
    value.getClass();
  price_ = value;
    
    }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergePrice(io.bokun.inventory.common.api.grpc.Price value) {
    value.getClass();
  if (price_ != null &&
        price_ != io.bokun.inventory.common.api.grpc.Price.getDefaultInstance()) {
      price_ =
        io.bokun.inventory.common.api.grpc.Price.newBuilder(price_).mergeFrom(value).buildPartial();
    } else {
      price_ = value;
    }
    
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
   */
  private void clearPrice() {  price_ = null;
    
  }

  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice)
      io.bokun.inventory.common.api.grpc.PricingCategoryWithPriceOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string pricingCategoryId = 1;</code>
     * @return The pricingCategoryId.
     */
    @java.lang.Override
    public java.lang.String getPricingCategoryId() {
      return instance.getPricingCategoryId();
    }
    /**
     * <code>string pricingCategoryId = 1;</code>
     * @return The bytes for pricingCategoryId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPricingCategoryIdBytes() {
      return instance.getPricingCategoryIdBytes();
    }
    /**
     * <code>string pricingCategoryId = 1;</code>
     * @param value The pricingCategoryId to set.
     * @return This builder for chaining.
     */
    public Builder setPricingCategoryId(
        java.lang.String value) {
      copyOnWrite();
      instance.setPricingCategoryId(value);
      return this;
    }
    /**
     * <code>string pricingCategoryId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPricingCategoryId() {
      copyOnWrite();
      instance.clearPricingCategoryId();
      return this;
    }
    /**
     * <code>string pricingCategoryId = 1;</code>
     * @param value The bytes for pricingCategoryId to set.
     * @return This builder for chaining.
     */
    public Builder setPricingCategoryIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setPricingCategoryIdBytes(value);
      return this;
    }

    /**
     * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
     */
    @java.lang.Override
    public boolean hasPrice() {
      return instance.hasPrice();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.Price getPrice() {
      return instance.getPrice();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
     */
    public Builder setPrice(io.bokun.inventory.common.api.grpc.Price value) {
      copyOnWrite();
      instance.setPrice(value);
      return this;
      }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
     */
    public Builder setPrice(
        io.bokun.inventory.common.api.grpc.Price.Builder builderForValue) {
      copyOnWrite();
      instance.setPrice(builderForValue.build());
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
     */
    public Builder mergePrice(io.bokun.inventory.common.api.grpc.Price value) {
      copyOnWrite();
      instance.mergePrice(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.Price price = 2;</code>
     */
    public Builder clearPrice() {  copyOnWrite();
      instance.clearPrice();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "pricingCategoryId_",
            "price_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\t" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice)
  private static final io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice DEFAULT_INSTANCE;
  static {
    PricingCategoryWithPrice defaultInstance = new PricingCategoryWithPrice();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      PricingCategoryWithPrice.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.PricingCategoryWithPrice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<PricingCategoryWithPrice> PARSER;

  public static com.google.protobuf.Parser<PricingCategoryWithPrice> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

