// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * <pre>
 * All fields mandatory
 * </pre>
 *
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.Price}
 */
public  final class Price extends
    com.google.protobuf.GeneratedMessageLite<
        Price, Price.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.Price)
    PriceOrBuilder {
  private Price() {
    currency_ = "";
    amount_ = "";
  }
  public static final int CURRENCY_FIELD_NUMBER = 1;
  private java.lang.String currency_;
  /**
   * <pre>
   * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
   * </pre>
   *
   * <code>string currency = 1;</code>
   * @return The currency.
   */
  @java.lang.Override
  public java.lang.String getCurrency() {
    return currency_;
  }
  /**
   * <pre>
   * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
   * </pre>
   *
   * <code>string currency = 1;</code>
   * @return The bytes for currency.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCurrencyBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(currency_);
  }
  /**
   * <pre>
   * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
   * </pre>
   *
   * <code>string currency = 1;</code>
   * @param value The currency to set.
   */
  private void setCurrency(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    currency_ = value;
  }
  /**
   * <pre>
   * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
   * </pre>
   *
   * <code>string currency = 1;</code>
   */
  private void clearCurrency() {
    
    currency_ = getDefaultInstance().getCurrency();
  }
  /**
   * <pre>
   * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
   * </pre>
   *
   * <code>string currency = 1;</code>
   * @param value The bytes for currency to set.
   */
  private void setCurrencyBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    currency_ = value.toStringUtf8();
    
  }

  public static final int AMOUNT_FIELD_NUMBER = 2;
  private java.lang.String amount_;
  /**
   * <pre>
   * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
   * </pre>
   *
   * <code>string amount = 2;</code>
   * @return The amount.
   */
  @java.lang.Override
  public java.lang.String getAmount() {
    return amount_;
  }
  /**
   * <pre>
   * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
   * </pre>
   *
   * <code>string amount = 2;</code>
   * @return The bytes for amount.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getAmountBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(amount_);
  }
  /**
   * <pre>
   * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
   * </pre>
   *
   * <code>string amount = 2;</code>
   * @param value The amount to set.
   */
  private void setAmount(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    amount_ = value;
  }
  /**
   * <pre>
   * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
   * </pre>
   *
   * <code>string amount = 2;</code>
   */
  private void clearAmount() {
    
    amount_ = getDefaultInstance().getAmount();
  }
  /**
   * <pre>
   * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
   * </pre>
   *
   * <code>string amount = 2;</code>
   * @param value The bytes for amount to set.
   */
  private void setAmountBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    amount_ = value.toStringUtf8();
    
  }

  public static io.bokun.inventory.common.api.grpc.Price parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Price parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.Price prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * All fields mandatory
   * </pre>
   *
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.Price}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.Price, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.Price)
      io.bokun.inventory.common.api.grpc.PriceOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.Price.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
     * </pre>
     *
     * <code>string currency = 1;</code>
     * @return The currency.
     */
    @java.lang.Override
    public java.lang.String getCurrency() {
      return instance.getCurrency();
    }
    /**
     * <pre>
     * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
     * </pre>
     *
     * <code>string currency = 1;</code>
     * @return The bytes for currency.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCurrencyBytes() {
      return instance.getCurrencyBytes();
    }
    /**
     * <pre>
     * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
     * </pre>
     *
     * <code>string currency = 1;</code>
     * @param value The currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrency(
        java.lang.String value) {
      copyOnWrite();
      instance.setCurrency(value);
      return this;
    }
    /**
     * <pre>
     * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
     * </pre>
     *
     * <code>string currency = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCurrency() {
      copyOnWrite();
      instance.clearCurrency();
      return this;
    }
    /**
     * <pre>
     * ISO 4217 currency code (such as USD, EUR, GBP, etc.). Mandatory.
     * </pre>
     *
     * <code>string currency = 1;</code>
     * @param value The bytes for currency to set.
     * @return This builder for chaining.
     */
    public Builder setCurrencyBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setCurrencyBytes(value);
      return this;
    }

    /**
     * <pre>
     * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
     * </pre>
     *
     * <code>string amount = 2;</code>
     * @return The amount.
     */
    @java.lang.Override
    public java.lang.String getAmount() {
      return instance.getAmount();
    }
    /**
     * <pre>
     * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
     * </pre>
     *
     * <code>string amount = 2;</code>
     * @return The bytes for amount.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getAmountBytes() {
      return instance.getAmountBytes();
    }
    /**
     * <pre>
     * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
     * </pre>
     *
     * <code>string amount = 2;</code>
     * @param value The amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmount(
        java.lang.String value) {
      copyOnWrite();
      instance.setAmount(value);
      return this;
    }
    /**
     * <pre>
     * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
     * </pre>
     *
     * <code>string amount = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAmount() {
      copyOnWrite();
      instance.clearAmount();
      return this;
    }
    /**
     * <pre>
     * Can't use double because of precision loss. Will convert to BigDecimal when data arrives in Java. Mandatory.
     * </pre>
     *
     * <code>string amount = 2;</code>
     * @param value The bytes for amount to set.
     * @return This builder for chaining.
     */
    public Builder setAmountBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setAmountBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.Price)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.Price();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "currency_",
            "amount_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.Price> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.Price.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.Price>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.Price)
  private static final io.bokun.inventory.common.api.grpc.Price DEFAULT_INSTANCE;
  static {
    Price defaultInstance = new Price();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Price.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.Price getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Price> PARSER;

  public static com.google.protobuf.Parser<Price> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

