// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface QrTicketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.QrTicket)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * String which is used to generate barcode from. Mandatory.
   * </pre>
   *
   * <code>string ticketBarcode = 1;</code>
   * @return The ticketBarcode.
   */
  java.lang.String getTicketBarcode();
  /**
   * <pre>
   * String which is used to generate barcode from. Mandatory.
   * </pre>
   *
   * <code>string ticketBarcode = 1;</code>
   * @return The bytes for ticketBarcode.
   */
  com.google.protobuf.ByteString
      getTicketBarcodeBytes();

  /**
   * <pre>
   * String which may be used to verify ticket manually in case if there is no connection for QR code scanner. Optional.
   * </pre>
   *
   * <code>string offlineCode = 2;</code>
   * @return The offlineCode.
   */
  java.lang.String getOfflineCode();
  /**
   * <pre>
   * String which may be used to verify ticket manually in case if there is no connection for QR code scanner. Optional.
   * </pre>
   *
   * <code>string offlineCode = 2;</code>
   * @return The bytes for offlineCode.
   */
  com.google.protobuf.ByteString
      getOfflineCodeBytes();
}
