// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.RateWithPrice}
 */
public  final class RateWithPrice extends
    com.google.protobuf.GeneratedMessageLite<
        RateWithPrice, RateWithPrice.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.RateWithPrice)
    RateWithPriceOrBuilder {
  private RateWithPrice() {
    rateId_ = "";
  }
  private int pricingOptionsCase_ = 0;
  private java.lang.Object pricingOptions_;
  public enum PricingOptionsCase {
    PRICEPERPERSON(3),
    PRICEPERBOOKING(4),
    PRICINGOPTIONS_NOT_SET(0);
    private final int value;
    private PricingOptionsCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static PricingOptionsCase valueOf(int value) {
      return forNumber(value);
    }

    public static PricingOptionsCase forNumber(int value) {
      switch (value) {
        case 3: return PRICEPERPERSON;
        case 4: return PRICEPERBOOKING;
        case 0: return PRICINGOPTIONS_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public PricingOptionsCase
  getPricingOptionsCase() {
    return PricingOptionsCase.forNumber(
        pricingOptionsCase_);
  }

  private void clearPricingOptions() {
    pricingOptionsCase_ = 0;
    pricingOptions_ = null;
  }

  public static final int RATEID_FIELD_NUMBER = 1;
  private java.lang.String rateId_;
  /**
   * <pre>
   * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
   * superficial rate.
   * </pre>
   *
   * <code>string rateId = 1;</code>
   * @return The rateId.
   */
  @java.lang.Override
  public java.lang.String getRateId() {
    return rateId_;
  }
  /**
   * <pre>
   * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
   * superficial rate.
   * </pre>
   *
   * <code>string rateId = 1;</code>
   * @return The bytes for rateId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getRateIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(rateId_);
  }
  /**
   * <pre>
   * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
   * superficial rate.
   * </pre>
   *
   * <code>string rateId = 1;</code>
   * @param value The rateId to set.
   */
  private void setRateId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    rateId_ = value;
  }
  /**
   * <pre>
   * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
   * superficial rate.
   * </pre>
   *
   * <code>string rateId = 1;</code>
   */
  private void clearRateId() {
    
    rateId_ = getDefaultInstance().getRateId();
  }
  /**
   * <pre>
   * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
   * superficial rate.
   * </pre>
   *
   * <code>string rateId = 1;</code>
   * @param value The bytes for rateId to set.
   */
  private void setRateIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    rateId_ = value.toStringUtf8();
    
  }

  public static final int PRICEPERPERSON_FIELD_NUMBER = 3;
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
   */
  @java.lang.Override
  public boolean hasPricePerPerson() {
    return pricingOptionsCase_ == 3;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.PricePerPerson getPricePerPerson() {
    if (pricingOptionsCase_ == 3) {
       return (io.bokun.inventory.common.api.grpc.PricePerPerson) pricingOptions_;
    }
    return io.bokun.inventory.common.api.grpc.PricePerPerson.getDefaultInstance();
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
   */
  private void setPricePerPerson(io.bokun.inventory.common.api.grpc.PricePerPerson value) {
    value.getClass();
  pricingOptions_ = value;
    pricingOptionsCase_ = 3;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
   */
  private void mergePricePerPerson(io.bokun.inventory.common.api.grpc.PricePerPerson value) {
    value.getClass();
  if (pricingOptionsCase_ == 3 &&
        pricingOptions_ != io.bokun.inventory.common.api.grpc.PricePerPerson.getDefaultInstance()) {
      pricingOptions_ = io.bokun.inventory.common.api.grpc.PricePerPerson.newBuilder((io.bokun.inventory.common.api.grpc.PricePerPerson) pricingOptions_)
          .mergeFrom(value).buildPartial();
    } else {
      pricingOptions_ = value;
    }
    pricingOptionsCase_ = 3;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
   */
  private void clearPricePerPerson() {
    if (pricingOptionsCase_ == 3) {
      pricingOptionsCase_ = 0;
      pricingOptions_ = null;
    }
  }

  public static final int PRICEPERBOOKING_FIELD_NUMBER = 4;
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
   */
  @java.lang.Override
  public boolean hasPricePerBooking() {
    return pricingOptionsCase_ == 4;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
   */
  @java.lang.Override
  public io.bokun.inventory.common.api.grpc.PricePerBooking getPricePerBooking() {
    if (pricingOptionsCase_ == 4) {
       return (io.bokun.inventory.common.api.grpc.PricePerBooking) pricingOptions_;
    }
    return io.bokun.inventory.common.api.grpc.PricePerBooking.getDefaultInstance();
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
   */
  private void setPricePerBooking(io.bokun.inventory.common.api.grpc.PricePerBooking value) {
    value.getClass();
  pricingOptions_ = value;
    pricingOptionsCase_ = 4;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
   */
  private void mergePricePerBooking(io.bokun.inventory.common.api.grpc.PricePerBooking value) {
    value.getClass();
  if (pricingOptionsCase_ == 4 &&
        pricingOptions_ != io.bokun.inventory.common.api.grpc.PricePerBooking.getDefaultInstance()) {
      pricingOptions_ = io.bokun.inventory.common.api.grpc.PricePerBooking.newBuilder((io.bokun.inventory.common.api.grpc.PricePerBooking) pricingOptions_)
          .mergeFrom(value).buildPartial();
    } else {
      pricingOptions_ = value;
    }
    pricingOptionsCase_ = 4;
  }
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
   */
  private void clearPricePerBooking() {
    if (pricingOptionsCase_ == 4) {
      pricingOptionsCase_ = 0;
      pricingOptions_ = null;
    }
  }

  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.RateWithPrice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.RateWithPrice prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.RateWithPrice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.RateWithPrice, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.RateWithPrice)
      io.bokun.inventory.common.api.grpc.RateWithPriceOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.RateWithPrice.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public PricingOptionsCase
        getPricingOptionsCase() {
      return instance.getPricingOptionsCase();
    }

    public Builder clearPricingOptions() {
      copyOnWrite();
      instance.clearPricingOptions();
      return this;
    }


    /**
     * <pre>
     * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
     * superficial rate.
     * </pre>
     *
     * <code>string rateId = 1;</code>
     * @return The rateId.
     */
    @java.lang.Override
    public java.lang.String getRateId() {
      return instance.getRateId();
    }
    /**
     * <pre>
     * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
     * superficial rate.
     * </pre>
     *
     * <code>string rateId = 1;</code>
     * @return The bytes for rateId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRateIdBytes() {
      return instance.getRateIdBytes();
    }
    /**
     * <pre>
     * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
     * superficial rate.
     * </pre>
     *
     * <code>string rateId = 1;</code>
     * @param value The rateId to set.
     * @return This builder for chaining.
     */
    public Builder setRateId(
        java.lang.String value) {
      copyOnWrite();
      instance.setRateId(value);
      return this;
    }
    /**
     * <pre>
     * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
     * superficial rate.
     * </pre>
     *
     * <code>string rateId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRateId() {
      copyOnWrite();
      instance.clearRateId();
      return this;
    }
    /**
     * <pre>
     * What rate ("12 hour rate", "24 hour rate"). Mandatory. If the remote end does not support rates, plugins should at least return some
     * superficial rate.
     * </pre>
     *
     * <code>string rateId = 1;</code>
     * @param value The bytes for rateId to set.
     * @return This builder for chaining.
     */
    public Builder setRateIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setRateIdBytes(value);
      return this;
    }

    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
     */
    @java.lang.Override
    public boolean hasPricePerPerson() {
      return instance.hasPricePerPerson();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.PricePerPerson getPricePerPerson() {
      return instance.getPricePerPerson();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
     */
    public Builder setPricePerPerson(io.bokun.inventory.common.api.grpc.PricePerPerson value) {
      copyOnWrite();
      instance.setPricePerPerson(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
     */
    public Builder setPricePerPerson(
        io.bokun.inventory.common.api.grpc.PricePerPerson.Builder builderForValue) {
      copyOnWrite();
      instance.setPricePerPerson(builderForValue.build());
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
     */
    public Builder mergePricePerPerson(io.bokun.inventory.common.api.grpc.PricePerPerson value) {
      copyOnWrite();
      instance.mergePricePerPerson(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerPerson pricePerPerson = 3;</code>
     */
    public Builder clearPricePerPerson() {
      copyOnWrite();
      instance.clearPricePerPerson();
      return this;
    }

    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
     */
    @java.lang.Override
    public boolean hasPricePerBooking() {
      return instance.hasPricePerBooking();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
     */
    @java.lang.Override
    public io.bokun.inventory.common.api.grpc.PricePerBooking getPricePerBooking() {
      return instance.getPricePerBooking();
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
     */
    public Builder setPricePerBooking(io.bokun.inventory.common.api.grpc.PricePerBooking value) {
      copyOnWrite();
      instance.setPricePerBooking(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
     */
    public Builder setPricePerBooking(
        io.bokun.inventory.common.api.grpc.PricePerBooking.Builder builderForValue) {
      copyOnWrite();
      instance.setPricePerBooking(builderForValue.build());
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
     */
    public Builder mergePricePerBooking(io.bokun.inventory.common.api.grpc.PricePerBooking value) {
      copyOnWrite();
      instance.mergePricePerBooking(value);
      return this;
    }
    /**
     * <code>.io.bokun.inventory.common.api.grpc.PricePerBooking pricePerBooking = 4;</code>
     */
    public Builder clearPricePerBooking() {
      copyOnWrite();
      instance.clearPricePerBooking();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.RateWithPrice)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.RateWithPrice();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "pricingOptions_",
            "pricingOptionsCase_",
            "rateId_",
            io.bokun.inventory.common.api.grpc.PricePerPerson.class,
            io.bokun.inventory.common.api.grpc.PricePerBooking.class,
          };
          java.lang.String info =
              "\u0000\u0003\u0001\u0000\u0001\u0004\u0003\u0000\u0000\u0000\u0001\u0208\u0003<\u0000" +
              "\u0004<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.RateWithPrice> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.RateWithPrice.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.RateWithPrice>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.RateWithPrice)
  private static final io.bokun.inventory.common.api.grpc.RateWithPrice DEFAULT_INSTANCE;
  static {
    RateWithPrice defaultInstance = new RateWithPrice();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      RateWithPrice.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.RateWithPrice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<RateWithPrice> PARSER;

  public static com.google.protobuf.Parser<RateWithPrice> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

