// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface SuccessfulCancellationOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.SuccessfulCancellation)
    com.google.protobuf.MessageLiteOrBuilder {
}
