// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

public interface TicketOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.common.api.grpc.Ticket)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * &#64;see TicketType#BINARY
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BinaryTicket binaryTicket = 1;</code>
   * @return Whether the binaryTicket field is set.
   */
  boolean hasBinaryTicket();
  /**
   * <pre>
   * &#64;see TicketType#BINARY
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BinaryTicket binaryTicket = 1;</code>
   * @return The binaryTicket.
   */
  io.bokun.inventory.common.api.grpc.BinaryTicket getBinaryTicket();

  /**
   * <pre>
   * &#64;see TicketType#QR_CODE
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.QrTicket qrTicket = 2;</code>
   * @return Whether the qrTicket field is set.
   */
  boolean hasQrTicket();
  /**
   * <pre>
   * &#64;see TicketType#QR_CODE
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.QrTicket qrTicket = 2;</code>
   * @return The qrTicket.
   */
  io.bokun.inventory.common.api.grpc.QrTicket getQrTicket();

  /**
   * <pre>
   * &#64;see TicketType#DATA_MATRIX
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.DataMatrixTicket dataMatrixTicket = 3;</code>
   * @return Whether the dataMatrixTicket field is set.
   */
  boolean hasDataMatrixTicket();
  /**
   * <pre>
   * &#64;see TicketType#DATA_MATRIX
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.DataMatrixTicket dataMatrixTicket = 3;</code>
   * @return The dataMatrixTicket.
   */
  io.bokun.inventory.common.api.grpc.DataMatrixTicket getDataMatrixTicket();

  /**
   * <pre>
   * For when ticket expiry dates are dynamic in the plugin and should override the one set in the platform. Optional.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Date expiryDate = 4;</code>
   * @return Whether the expiryDate field is set.
   */
  boolean hasExpiryDate();
  /**
   * <pre>
   * For when ticket expiry dates are dynamic in the plugin and should override the one set in the platform. Optional.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Date expiryDate = 4;</code>
   * @return The expiryDate.
   */
  io.bokun.inventory.common.api.grpc.Date getExpiryDate();

  public io.bokun.inventory.common.api.grpc.Ticket.TicketCase getTicketCase();
}
