// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common.proto

package io.bokun.inventory.common.api.grpc;

/**
 * <pre>
 * All fields mandatory
 * </pre>
 *
 * Protobuf type {@code io.bokun.inventory.common.api.grpc.Time}
 */
public  final class Time extends
    com.google.protobuf.GeneratedMessageLite<
        Time, Time.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.common.api.grpc.Time)
    TimeOrBuilder {
  private Time() {
  }
  public static final int HOUR_FIELD_NUMBER = 1;
  private int hour_;
  /**
   * <code>int32 hour = 1;</code>
   * @return The hour.
   */
  @java.lang.Override
  public int getHour() {
    return hour_;
  }
  /**
   * <code>int32 hour = 1;</code>
   * @param value The hour to set.
   */
  private void setHour(int value) {
    
    hour_ = value;
  }
  /**
   * <code>int32 hour = 1;</code>
   */
  private void clearHour() {
    
    hour_ = 0;
  }

  public static final int MINUTE_FIELD_NUMBER = 2;
  private int minute_;
  /**
   * <code>int32 minute = 2;</code>
   * @return The minute.
   */
  @java.lang.Override
  public int getMinute() {
    return minute_;
  }
  /**
   * <code>int32 minute = 2;</code>
   * @param value The minute to set.
   */
  private void setMinute(int value) {
    
    minute_ = value;
  }
  /**
   * <code>int32 minute = 2;</code>
   */
  private void clearMinute() {
    
    minute_ = 0;
  }

  public static io.bokun.inventory.common.api.grpc.Time parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.common.api.grpc.Time parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.common.api.grpc.Time prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * <pre>
   * All fields mandatory
   * </pre>
   *
   * Protobuf type {@code io.bokun.inventory.common.api.grpc.Time}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.common.api.grpc.Time, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.common.api.grpc.Time)
      io.bokun.inventory.common.api.grpc.TimeOrBuilder {
    // Construct using io.bokun.inventory.common.api.grpc.Time.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>int32 hour = 1;</code>
     * @return The hour.
     */
    @java.lang.Override
    public int getHour() {
      return instance.getHour();
    }
    /**
     * <code>int32 hour = 1;</code>
     * @param value The hour to set.
     * @return This builder for chaining.
     */
    public Builder setHour(int value) {
      copyOnWrite();
      instance.setHour(value);
      return this;
    }
    /**
     * <code>int32 hour = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearHour() {
      copyOnWrite();
      instance.clearHour();
      return this;
    }

    /**
     * <code>int32 minute = 2;</code>
     * @return The minute.
     */
    @java.lang.Override
    public int getMinute() {
      return instance.getMinute();
    }
    /**
     * <code>int32 minute = 2;</code>
     * @param value The minute to set.
     * @return This builder for chaining.
     */
    public Builder setMinute(int value) {
      copyOnWrite();
      instance.setMinute(value);
      return this;
    }
    /**
     * <code>int32 minute = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinute() {
      copyOnWrite();
      instance.clearMinute();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.common.api.grpc.Time)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.common.api.grpc.Time();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "hour_",
            "minute_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.common.api.grpc.Time> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.common.api.grpc.Time.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.common.api.grpc.Time>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.common.api.grpc.Time)
  private static final io.bokun.inventory.common.api.grpc.Time DEFAULT_INSTANCE;
  static {
    Time defaultInstance = new Time();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Time.class, defaultInstance);
  }

  public static io.bokun.inventory.common.api.grpc.Time getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Time> PARSER;

  public static com.google.protobuf.Parser<Time> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

