// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: availability_service.proto

package io.bokun.inventory.service.availability.grpc;

public interface GetAvailableProductsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.service.availability.grpc.GetAvailableProductsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Range of products we are looking in. Mandatory (must not be empty).
   * If any of given products is not mapped (inventory service is unaware of such product), it will be ignored.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct products = 1;</code>
   */
  java.util.List<io.bokun.inventory.service.common.grpc.BokunProduct> 
      getProductsList();
  /**
   * <pre>
   * Range of products we are looking in. Mandatory (must not be empty).
   * If any of given products is not mapped (inventory service is unaware of such product), it will be ignored.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct products = 1;</code>
   */
  io.bokun.inventory.service.common.grpc.BokunProduct getProducts(int index);
  /**
   * <pre>
   * Range of products we are looking in. Mandatory (must not be empty).
   * If any of given products is not mapped (inventory service is unaware of such product), it will be ignored.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.service.common.grpc.BokunProduct products = 1;</code>
   */
  int getProductsCount();

  /**
   * <pre>
   * What date range are we searching for? Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.DatePeriod range = 2;</code>
   * @return Whether the range field is set.
   */
  boolean hasRange();
  /**
   * <pre>
   * What date range are we searching for? Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.DatePeriod range = 2;</code>
   * @return The range.
   */
  io.bokun.inventory.common.api.grpc.DatePeriod getRange();

  /**
   * <pre>
   * Required capacity. Mandatory.
   * </pre>
   *
   * <code>int32 capacity = 3;</code>
   * @return The capacity.
   */
  int getCapacity();
}
