// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: availability_service.proto

package io.bokun.inventory.service.availability.grpc;

public interface GetProductAvailabilityRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.service.availability.grpc.GetProductAvailabilityRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * For which Bokun product to find availability/prices for? Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.service.common.grpc.BokunProduct product = 1;</code>
   * @return Whether the product field is set.
   */
  boolean hasProduct();
  /**
   * <pre>
   * For which Bokun product to find availability/prices for? Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.service.common.grpc.BokunProduct product = 1;</code>
   * @return The product.
   */
  io.bokun.inventory.service.common.grpc.BokunProduct getProduct();

  /**
   * <pre>
   * For which range to find availability/prices for? Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.DatePeriod range = 2;</code>
   * @return Whether the range field is set.
   */
  boolean hasRange();
  /**
   * <pre>
   * For which range to find availability/prices for? Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.DatePeriod range = 2;</code>
   * @return The range.
   */
  io.bokun.inventory.common.api.grpc.DatePeriod getRange();
}
