// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: provisioning_service.proto

package io.bokun.inventory.service.provisioning.grpc;

/**
 * Protobuf type {@code io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse}
 */
public  final class GetBuildInfoResponse extends
    com.google.protobuf.GeneratedMessageLite<
        GetBuildInfoResponse, GetBuildInfoResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse)
    GetBuildInfoResponseOrBuilder {
  private GetBuildInfoResponse() {
    buildInformation_ = "";
  }
  public static final int BUILDINFORMATION_FIELD_NUMBER = 1;
  private java.lang.String buildInformation_;
  /**
   * <pre>
   * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
   * </pre>
   *
   * <code>string buildInformation = 1;</code>
   * @return The buildInformation.
   */
  @java.lang.Override
  public java.lang.String getBuildInformation() {
    return buildInformation_;
  }
  /**
   * <pre>
   * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
   * </pre>
   *
   * <code>string buildInformation = 1;</code>
   * @return The bytes for buildInformation.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBuildInformationBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(buildInformation_);
  }
  /**
   * <pre>
   * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
   * </pre>
   *
   * <code>string buildInformation = 1;</code>
   * @param value The buildInformation to set.
   */
  private void setBuildInformation(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    buildInformation_ = value;
  }
  /**
   * <pre>
   * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
   * </pre>
   *
   * <code>string buildInformation = 1;</code>
   */
  private void clearBuildInformation() {
    
    buildInformation_ = getDefaultInstance().getBuildInformation();
  }
  /**
   * <pre>
   * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
   * </pre>
   *
   * <code>string buildInformation = 1;</code>
   * @param value The bytes for buildInformation to set.
   */
  private void setBuildInformationBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    buildInformation_ = value.toStringUtf8();
    
  }

  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse)
      io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponseOrBuilder {
    // Construct using io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
     * </pre>
     *
     * <code>string buildInformation = 1;</code>
     * @return The buildInformation.
     */
    @java.lang.Override
    public java.lang.String getBuildInformation() {
      return instance.getBuildInformation();
    }
    /**
     * <pre>
     * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
     * </pre>
     *
     * <code>string buildInformation = 1;</code>
     * @return The bytes for buildInformation.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getBuildInformationBytes() {
      return instance.getBuildInformationBytes();
    }
    /**
     * <pre>
     * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
     * </pre>
     *
     * <code>string buildInformation = 1;</code>
     * @param value The buildInformation to set.
     * @return This builder for chaining.
     */
    public Builder setBuildInformation(
        java.lang.String value) {
      copyOnWrite();
      instance.setBuildInformation(value);
      return this;
    }
    /**
     * <pre>
     * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
     * </pre>
     *
     * <code>string buildInformation = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBuildInformation() {
      copyOnWrite();
      instance.clearBuildInformation();
      return this;
    }
    /**
     * <pre>
     * May contain elements such as branch, build number, etc. Does not imply any particular structure. Mandatory.
     * </pre>
     *
     * <code>string buildInformation = 1;</code>
     * @param value The bytes for buildInformation to set.
     * @return This builder for chaining.
     */
    public Builder setBuildInformationBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBuildInformationBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "buildInformation_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse> parser = PARSER;
        if (parser == null) {
          synchronized (io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse)
  private static final io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse DEFAULT_INSTANCE;
  static {
    GetBuildInfoResponse defaultInstance = new GetBuildInfoResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GetBuildInfoResponse.class, defaultInstance);
  }

  public static io.bokun.inventory.service.provisioning.grpc.GetBuildInfoResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GetBuildInfoResponse> PARSER;

  public static com.google.protobuf.Parser<GetBuildInfoResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

