/*
 * Channel Manager REST API
 * Channel Manager REST API. You can find out more about Channel Manager [here](https://www.bokun.io/sell/channel-manager).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bokun.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.bokun.inventory.plugin.api.rest;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BinaryTicket
 */

public class BinaryTicket {
  @SerializedName("ticketContent")
  private String ticketContent = null;

  public BinaryTicket ticketContent(String ticketContent) {
    this.ticketContent = ticketContent;
    return this;
  }

   /**
   * representation of ticket in bytes, Base64 encoded
   * @return ticketContent
  **/
  @ApiModelProperty(required = true, value = "representation of ticket in bytes, Base64 encoded")
  public String getTicketContent() {
    return ticketContent;
  }

  public void setTicketContent(String ticketContent) {
    this.ticketContent = ticketContent;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BinaryTicket binaryTicket = (BinaryTicket) o;
    return Objects.equals(this.ticketContent, binaryTicket.ticketContent);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketContent);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BinaryTicket {\n");
    
    sb.append("    ticketContent: ").append(toIndentedString(ticketContent)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

