/*
 * Channel Manager REST API
 * Channel Manager REST API. You can find out more about Channel Manager [here](https://www.bokun.io/sell/channel-manager).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bokun.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.bokun.inventory.plugin.api.rest;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.bokun.inventory.plugin.api.rest.TicketSupport;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ConfirmationData
 */

public class ConfirmationData {
  @SerializedName("ticketSupport")
  private TicketSupport ticketSupport = null;

  public ConfirmationData ticketSupport(TicketSupport ticketSupport) {
    this.ticketSupport = ticketSupport;
    return this;
  }

   /**
   * Get ticketSupport
   * @return ticketSupport
  **/
  @ApiModelProperty(required = true, value = "")
  public TicketSupport getTicketSupport() {
    return ticketSupport;
  }

  public void setTicketSupport(TicketSupport ticketSupport) {
    this.ticketSupport = ticketSupport;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConfirmationData confirmationData = (ConfirmationData) o;
    return Objects.equals(this.ticketSupport, confirmationData.ticketSupport);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ticketSupport);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConfirmationData {\n");
    
    sb.append("    ticketSupport: ").append(toIndentedString(ticketSupport)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

