/*
 * Channel Manager REST API
 * Channel Manager REST API. You can find out more about Channel Manager [here](https://www.bokun.io/sell/channel-manager).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bokun.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.bokun.inventory.plugin.api.rest;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.bokun.inventory.plugin.api.rest.PricingCategoryWithPrice;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * PricePerPerson
 */

public class PricePerPerson {
  @SerializedName("pricingCategoryWithPrice")
  private List<PricingCategoryWithPrice> pricingCategoryWithPrice = new ArrayList<PricingCategoryWithPrice>();

  public PricePerPerson pricingCategoryWithPrice(List<PricingCategoryWithPrice> pricingCategoryWithPrice) {
    this.pricingCategoryWithPrice = pricingCategoryWithPrice;
    return this;
  }

  public PricePerPerson addPricingCategoryWithPriceItem(PricingCategoryWithPrice pricingCategoryWithPriceItem) {
    this.pricingCategoryWithPrice.add(pricingCategoryWithPriceItem);
    return this;
  }

   /**
   * Get pricingCategoryWithPrice
   * @return pricingCategoryWithPrice
  **/
  @ApiModelProperty(required = true, value = "")
  public List<PricingCategoryWithPrice> getPricingCategoryWithPrice() {
    return pricingCategoryWithPrice;
  }

  public void setPricingCategoryWithPrice(List<PricingCategoryWithPrice> pricingCategoryWithPrice) {
    this.pricingCategoryWithPrice = pricingCategoryWithPrice;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PricePerPerson pricePerPerson = (PricePerPerson) o;
    return Objects.equals(this.pricingCategoryWithPrice, pricePerPerson.pricingCategoryWithPrice);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pricingCategoryWithPrice);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PricePerPerson {\n");
    
    sb.append("    pricingCategoryWithPrice: ").append(toIndentedString(pricingCategoryWithPrice)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

