/*
 * Channel Manager REST API
 * Channel Manager REST API. You can find out more about Channel Manager [here](https://www.bokun.io/sell/channel-manager).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bokun.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.bokun.inventory.plugin.api.rest;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets ProductCategory
 */
@JsonAdapter(ProductCategory.Adapter.class)
public enum ProductCategory {
  
  ACCOMMODATION("ACCOMMODATION"),
  
  ACTIVITIES("ACTIVITIES"),
  
  CAR_RENTALS("CAR_RENTALS"),
  
  TRANSPORT("TRANSPORT");

  private String value;

  ProductCategory(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static ProductCategory fromValue(String text) {
    for (ProductCategory b : ProductCategory.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<ProductCategory> {
    @Override
    public void write(final JsonWriter jsonWriter, final ProductCategory enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public ProductCategory read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return ProductCategory.fromValue(String.valueOf(value));
    }
  }
}

