/*
 * Channel Manager REST API
 * Channel Manager REST API. You can find out more about Channel Manager [here](https://www.bokun.io/sell/channel-manager).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: support@bokun.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.bokun.inventory.plugin.api.rest;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.bokun.inventory.plugin.api.rest.OpeningHours;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SeasonalOpeningHours
 */

public class SeasonalOpeningHours {
  @SerializedName("startMonth")
  private Integer startMonth = null;

  @SerializedName("startDay")
  private Integer startDay = null;

  @SerializedName("endMonth")
  private Integer endMonth = null;

  @SerializedName("endDay")
  private Integer endDay = null;

  @SerializedName("openingHours")
  private OpeningHours openingHours = null;

  public SeasonalOpeningHours startMonth(Integer startMonth) {
    this.startMonth = startMonth;
    return this;
  }

   /**
   * Get startMonth
   * @return startMonth
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getStartMonth() {
    return startMonth;
  }

  public void setStartMonth(Integer startMonth) {
    this.startMonth = startMonth;
  }

  public SeasonalOpeningHours startDay(Integer startDay) {
    this.startDay = startDay;
    return this;
  }

   /**
   * Get startDay
   * @return startDay
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getStartDay() {
    return startDay;
  }

  public void setStartDay(Integer startDay) {
    this.startDay = startDay;
  }

  public SeasonalOpeningHours endMonth(Integer endMonth) {
    this.endMonth = endMonth;
    return this;
  }

   /**
   * Get endMonth
   * @return endMonth
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getEndMonth() {
    return endMonth;
  }

  public void setEndMonth(Integer endMonth) {
    this.endMonth = endMonth;
  }

  public SeasonalOpeningHours endDay(Integer endDay) {
    this.endDay = endDay;
    return this;
  }

   /**
   * Get endDay
   * @return endDay
  **/
  @ApiModelProperty(required = true, value = "")
  public Integer getEndDay() {
    return endDay;
  }

  public void setEndDay(Integer endDay) {
    this.endDay = endDay;
  }

  public SeasonalOpeningHours openingHours(OpeningHours openingHours) {
    this.openingHours = openingHours;
    return this;
  }

   /**
   * Get openingHours
   * @return openingHours
  **/
  @ApiModelProperty(required = true, value = "")
  public OpeningHours getOpeningHours() {
    return openingHours;
  }

  public void setOpeningHours(OpeningHours openingHours) {
    this.openingHours = openingHours;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SeasonalOpeningHours seasonalOpeningHours = (SeasonalOpeningHours) o;
    return Objects.equals(this.startMonth, seasonalOpeningHours.startMonth) &&
        Objects.equals(this.startDay, seasonalOpeningHours.startDay) &&
        Objects.equals(this.endMonth, seasonalOpeningHours.endMonth) &&
        Objects.equals(this.endDay, seasonalOpeningHours.endDay) &&
        Objects.equals(this.openingHours, seasonalOpeningHours.openingHours);
  }

  @Override
  public int hashCode() {
    return Objects.hash(startMonth, startDay, endMonth, endDay, openingHours);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SeasonalOpeningHours {\n");
    
    sb.append("    startMonth: ").append(toIndentedString(startMonth)).append("\n");
    sb.append("    startDay: ").append(toIndentedString(startDay)).append("\n");
    sb.append("    endMonth: ").append(toIndentedString(endMonth)).append("\n");
    sb.append("    endDay: ").append(toIndentedString(endDay)).append("\n");
    sb.append("    openingHours: ").append(toIndentedString(openingHours)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

