// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin_api.proto

package io.bokun.inventory.plugin.api.grpc;

public interface PluginConfigurationParameterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.plugin.api.grpc.PluginConfigurationParameter)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * names should be unique
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * names should be unique
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>.io.bokun.inventory.common.api.grpc.PluginParameterDataType type = 2;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <code>.io.bokun.inventory.common.api.grpc.PluginParameterDataType type = 2;</code>
   * @return The type.
   */
  io.bokun.inventory.common.api.grpc.PluginParameterDataType getType();

  /**
   * <code>bool required = 3;</code>
   * @return The required.
   */
  boolean getRequired();
}
