// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin_api.proto

package io.bokun.inventory.plugin.api.grpc;

public interface PluginDefinitionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.plugin.api.grpc.PluginDefinition)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Name of the definition. Mandatory.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the definition. Mandatory.
   * </pre>
   *
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Description of definition. Optional.
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Description of definition. Optional.
   * </pre>
   *
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * What does this plugin support? List may not be empty as such plugin would be utterly useless.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PluginCapability capabilities = 3;</code>
   * @return A list containing the capabilities.
   */
  java.util.List<io.bokun.inventory.common.api.grpc.PluginCapability> getCapabilitiesList();
  /**
   * <pre>
   * What does this plugin support? List may not be empty as such plugin would be utterly useless.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PluginCapability capabilities = 3;</code>
   * @return The count of capabilities.
   */
  int getCapabilitiesCount();
  /**
   * <pre>
   * What does this plugin support? List may not be empty as such plugin would be utterly useless.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PluginCapability capabilities = 3;</code>
   * @param index The index of the element to return.
   * @return The capabilities at the given index.
   */
  io.bokun.inventory.common.api.grpc.PluginCapability getCapabilities(int index);
  /**
   * <pre>
   * What does this plugin support? List may not be empty as such plugin would be utterly useless.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PluginCapability capabilities = 3;</code>
   * @return A list containing the enum numeric values on the wire for capabilities.
   */
  java.util.List<java.lang.Integer>
  getCapabilitiesValueList();
  /**
   * <pre>
   * What does this plugin support? List may not be empty as such plugin would be utterly useless.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PluginCapability capabilities = 3;</code>
   * @param index The index of the value to return.
   * @return The enum numeric value on the wire of capabilities at the given index.
   */
  int getCapabilitiesValue(int index);

  /**
   * <pre>
   * List of parameters this plugin should be configured with. Must contain at least one element.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.plugin.api.grpc.PluginConfigurationParameter parameters = 4;</code>
   */
  java.util.List<io.bokun.inventory.plugin.api.grpc.PluginConfigurationParameter> 
      getParametersList();
  /**
   * <pre>
   * List of parameters this plugin should be configured with. Must contain at least one element.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.plugin.api.grpc.PluginConfigurationParameter parameters = 4;</code>
   */
  io.bokun.inventory.plugin.api.grpc.PluginConfigurationParameter getParameters(int index);
  /**
   * <pre>
   * List of parameters this plugin should be configured with. Must contain at least one element.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.plugin.api.grpc.PluginConfigurationParameter parameters = 4;</code>
   */
  int getParametersCount();
}
