// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin_api.proto

package io.bokun.inventory.plugin.api.grpc;

public interface ReservationDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.plugin.api.grpc.ReservationData)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * Product id in external system. Mandatory.
   * </pre>
   *
   * <code>string productId = 2;</code>
   * @return The productId.
   */
  java.lang.String getProductId();
  /**
   * <pre>
   * Product id in external system. Mandatory.
   * </pre>
   *
   * <code>string productId = 2;</code>
   * @return The bytes for productId.
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <pre>
   * Contact of the customer who has reserved this booking (otherwise known as "lead customer"). Optional.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Contact customerContact = 3;</code>
   * @return Whether the customerContact field is set.
   */
  boolean hasCustomerContact();
  /**
   * <pre>
   * Contact of the customer who has reserved this booking (otherwise known as "lead customer"). Optional.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Contact customerContact = 3;</code>
   * @return The customerContact.
   */
  io.bokun.inventory.common.api.grpc.Contact getCustomerContact();

  /**
   * <pre>
   * Notes captured by a person who entered this booking (may also be customer itself if booked online). Optional.
   * </pre>
   *
   * <code>string notes = 4;</code>
   * @return The notes.
   */
  java.lang.String getNotes();
  /**
   * <pre>
   * Notes captured by a person who entered this booking (may also be customer itself if booked online). Optional.
   * </pre>
   *
   * <code>string notes = 4;</code>
   * @return The bytes for notes.
   */
  com.google.protobuf.ByteString
      getNotesBytes();

  /**
   * <pre>
   * For Date and Date&amp;Time products: day of the event should take place. Must match available date, as provided provided with ProductAvailabilityWithRatesResponse::date
   * For Pass products: pass expiry date (otherwise current date if pass has no expiration). The pass should be operational since the moment of purchase.
   * Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Date date = 5;</code>
   * @return Whether the date field is set.
   */
  boolean hasDate();
  /**
   * <pre>
   * For Date and Date&amp;Time products: day of the event should take place. Must match available date, as provided provided with ProductAvailabilityWithRatesResponse::date
   * For Pass products: pass expiry date (otherwise current date if pass has no expiration). The pass should be operational since the moment of purchase.
   * Mandatory.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Date date = 5;</code>
   * @return The date.
   */
  io.bokun.inventory.common.api.grpc.Date getDate();

  /**
   * <pre>
   * Desired start time. Mandatory if ProductDescription::bookingType is DATE_AND_TIME, otherwise null.
   * Must match available time, as provided with ProductAvailabilityWithRatesResponse::time
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Time time = 6;</code>
   * @return Whether the time field is set.
   */
  boolean hasTime();
  /**
   * <pre>
   * Desired start time. Mandatory if ProductDescription::bookingType is DATE_AND_TIME, otherwise null.
   * Must match available time, as provided with ProductAvailabilityWithRatesResponse::time
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.Time time = 6;</code>
   * @return The time.
   */
  io.bokun.inventory.common.api.grpc.Time getTime();

  /**
   * <pre>
   * Whether pickup is required. Only relevant if ProductDescription::pickupAvailable of booked product is true.
   * </pre>
   *
   * <code>bool pickupRequired = 7;</code>
   * @return The pickupRequired.
   */
  boolean getPickupRequired();

  /**
   * <pre>
   * Custom pickup location. Only relevant if ProductDescription::pickupAvailable and ProductDescription::customPickupPlaceAllowed are true and
   * if customer actually wants custom location.
   * </pre>
   *
   * <code>string customPickupPlace = 8;</code>
   * @return Whether the customPickupPlace field is set.
   */
  boolean hasCustomPickupPlace();
  /**
   * <pre>
   * Custom pickup location. Only relevant if ProductDescription::pickupAvailable and ProductDescription::customPickupPlaceAllowed are true and
   * if customer actually wants custom location.
   * </pre>
   *
   * <code>string customPickupPlace = 8;</code>
   * @return The customPickupPlace.
   */
  java.lang.String getCustomPickupPlace();
  /**
   * <pre>
   * Custom pickup location. Only relevant if ProductDescription::pickupAvailable and ProductDescription::customPickupPlaceAllowed are true and
   * if customer actually wants custom location.
   * </pre>
   *
   * <code>string customPickupPlace = 8;</code>
   * @return The bytes for customPickupPlace.
   */
  com.google.protobuf.ByteString
      getCustomPickupPlaceBytes();

  /**
   * <pre>
   * Pickup location. Only relevant if ProductDescription::pickupAvailable is true. Should only be set if ::pickupRequired is true.
   * Should match location from ProductDescription::pickupPlaces of booked product.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.PickupDropoffPlace predefinedPickupPlace = 9;</code>
   * @return Whether the predefinedPickupPlace field is set.
   */
  boolean hasPredefinedPickupPlace();
  /**
   * <pre>
   * Pickup location. Only relevant if ProductDescription::pickupAvailable is true. Should only be set if ::pickupRequired is true.
   * Should match location from ProductDescription::pickupPlaces of booked product.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.PickupDropoffPlace predefinedPickupPlace = 9;</code>
   * @return The predefinedPickupPlace.
   */
  io.bokun.inventory.common.api.grpc.PickupDropoffPlace getPredefinedPickupPlace();

  /**
   * <pre>
   * Whether drop off is required. Only relevant if ProductDescription::dropoffAvailable of booked product is true.
   * </pre>
   *
   * <code>bool dropoffRequired = 10;</code>
   * @return The dropoffRequired.
   */
  boolean getDropoffRequired();

  /**
   * <pre>
   * Custom drop off location. Only relevant if ProductDescription::dropoffAvailable and ProductDescription::customDropoffPlaceAllowed are true and
   * if customer actually wants custom location.
   * </pre>
   *
   * <code>string customDropoffPlace = 11;</code>
   * @return Whether the customDropoffPlace field is set.
   */
  boolean hasCustomDropoffPlace();
  /**
   * <pre>
   * Custom drop off location. Only relevant if ProductDescription::dropoffAvailable and ProductDescription::customDropoffPlaceAllowed are true and
   * if customer actually wants custom location.
   * </pre>
   *
   * <code>string customDropoffPlace = 11;</code>
   * @return The customDropoffPlace.
   */
  java.lang.String getCustomDropoffPlace();
  /**
   * <pre>
   * Custom drop off location. Only relevant if ProductDescription::dropoffAvailable and ProductDescription::customDropoffPlaceAllowed are true and
   * if customer actually wants custom location.
   * </pre>
   *
   * <code>string customDropoffPlace = 11;</code>
   * @return The bytes for customDropoffPlace.
   */
  com.google.protobuf.ByteString
      getCustomDropoffPlaceBytes();

  /**
   * <pre>
   * Drop off location. Only relevant if ProductDescription::dropoffAvailable is true. Should only be set if ::dropoffRequired is true.
   * Should match location from ProductDescription::dropoffPlaces of booked product.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.PickupDropoffPlace predefinedDropoffPlace = 12;</code>
   * @return Whether the predefinedDropoffPlace field is set.
   */
  boolean hasPredefinedDropoffPlace();
  /**
   * <pre>
   * Drop off location. Only relevant if ProductDescription::dropoffAvailable is true. Should only be set if ::dropoffRequired is true.
   * Should match location from ProductDescription::dropoffPlaces of booked product.
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.PickupDropoffPlace predefinedDropoffPlace = 12;</code>
   * @return The predefinedDropoffPlace.
   */
  io.bokun.inventory.common.api.grpc.PickupDropoffPlace getPredefinedDropoffPlace();

  /**
   * <pre>
   * A collection of reservations for each combination of rate/pricing category. Mandatory.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.Reservation reservations = 13;</code>
   */
  java.util.List<io.bokun.inventory.common.api.grpc.Reservation> 
      getReservationsList();
  /**
   * <pre>
   * A collection of reservations for each combination of rate/pricing category. Mandatory.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.Reservation reservations = 13;</code>
   */
  io.bokun.inventory.common.api.grpc.Reservation getReservations(int index);
  /**
   * <pre>
   * A collection of reservations for each combination of rate/pricing category. Mandatory.
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.Reservation reservations = 13;</code>
   */
  int getReservationsCount();

  /**
   * <pre>
   * This is some unique id which is *always* passed from the platform for this reservation. Plugins may ignore it, or may use this field in order
   * to make backrefrence from their own reservation/booking towards platform reservation/booking.
   * </pre>
   *
   * <code>string platformId = 14;</code>
   * @return The platformId.
   */
  java.lang.String getPlatformId();
  /**
   * <pre>
   * This is some unique id which is *always* passed from the platform for this reservation. Plugins may ignore it, or may use this field in order
   * to make backrefrence from their own reservation/booking towards platform reservation/booking.
   * </pre>
   *
   * <code>string platformId = 14;</code>
   * @return The bytes for platformId.
   */
  com.google.protobuf.ByteString
      getPlatformIdBytes();

  /**
   * <pre>
   * Booking source from which booking has originated
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSource bookingSource = 15;</code>
   * @return Whether the bookingSource field is set.
   */
  boolean hasBookingSource();
  /**
   * <pre>
   * Booking source from which booking has originated
   * </pre>
   *
   * <code>.io.bokun.inventory.common.api.grpc.BookingSource bookingSource = 15;</code>
   * @return The bookingSource.
   */
  io.bokun.inventory.common.api.grpc.BookingSource getBookingSource();

  /**
   * <pre>
   * In case this was booked by an external source (such as Expedia, Get Your Guide, Viator, etc.) this field will contain the reference number
   * which came from that source.
   * </pre>
   *
   * <code>string externalSaleId = 16;</code>
   * @return The externalSaleId.
   */
  java.lang.String getExternalSaleId();
  /**
   * <pre>
   * In case this was booked by an external source (such as Expedia, Get Your Guide, Viator, etc.) this field will contain the reference number
   * which came from that source.
   * </pre>
   *
   * <code>string externalSaleId = 16;</code>
   * @return The bytes for externalSaleId.
   */
  com.google.protobuf.ByteString
      getExternalSaleIdBytes();

  /**
   * <pre>
   * In case of agent booking - agent code. Optional
   * </pre>
   *
   * <code>string agentCode = 17;</code>
   * @return The agentCode.
   */
  java.lang.String getAgentCode();
  /**
   * <pre>
   * In case of agent booking - agent code. Optional
   * </pre>
   *
   * <code>string agentCode = 17;</code>
   * @return The bytes for agentCode.
   */
  com.google.protobuf.ByteString
      getAgentCodeBytes();

  /**
   * <pre>
   * This refers to a booking ID in Bokun platform. Sent at earliest possibility; guaranteed to be sent at confirmation stage.
   * </pre>
   *
   * <code>string platformBookingId = 18;</code>
   * @return The platformBookingId.
   */
  java.lang.String getPlatformBookingId();
  /**
   * <pre>
   * This refers to a booking ID in Bokun platform. Sent at earliest possibility; guaranteed to be sent at confirmation stage.
   * </pre>
   *
   * <code>string platformBookingId = 18;</code>
   * @return The bytes for platformBookingId.
   */
  com.google.protobuf.ByteString
      getPlatformBookingIdBytes();

  public io.bokun.inventory.plugin.api.grpc.ReservationData.PickupPlaceCase getPickupPlaceCase();

  public io.bokun.inventory.plugin.api.grpc.ReservationData.DropoffPlaceCase getDropoffPlaceCase();
}
