// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: plugin_api.proto

package io.bokun.inventory.plugin.api.grpc;

public interface SearchProductsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:io.bokun.inventory.plugin.api.grpc.SearchProductsRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   * plugin config parameters
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PluginConfigurationParameterValue parameters = 1;</code>
   */
  java.util.List<io.bokun.inventory.common.api.grpc.PluginConfigurationParameterValue> 
      getParametersList();
  /**
   * <pre>
   * plugin config parameters
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PluginConfigurationParameterValue parameters = 1;</code>
   */
  io.bokun.inventory.common.api.grpc.PluginConfigurationParameterValue getParameters(int index);
  /**
   * <pre>
   * plugin config parameters
   * </pre>
   *
   * <code>repeated .io.bokun.inventory.common.api.grpc.PluginConfigurationParameterValue parameters = 1;</code>
   */
  int getParametersCount();

  /**
   * <code>string productName = 2;</code>
   * @return The productName.
   */
  java.lang.String getProductName();
  /**
   * <code>string productName = 2;</code>
   * @return The bytes for productName.
   */
  com.google.protobuf.ByteString
      getProductNameBytes();

  /**
   * <pre>
   * ISO ALPHA-2 code
   * </pre>
   *
   * <code>string country = 3;</code>
   * @return The country.
   */
  java.lang.String getCountry();
  /**
   * <pre>
   * ISO ALPHA-2 code
   * </pre>
   *
   * <code>string country = 3;</code>
   * @return The bytes for country.
   */
  com.google.protobuf.ByteString
      getCountryBytes();

  /**
   * <pre>
   * city this product is served at. Optional
   * </pre>
   *
   * <code>string city = 4;</code>
   * @return The city.
   */
  java.lang.String getCity();
  /**
   * <pre>
   * city this product is served at. Optional
   * </pre>
   *
   * <code>string city = 4;</code>
   * @return The bytes for city.
   */
  com.google.protobuf.ByteString
      getCityBytes();
}
